### ISSUE TITLE
A search function would be nice

### ISSUE THREAD

**Issue by crissi** [barryvdh/laravel-translation-manager#1]
Sometimes I am in in doubt if I have already used a key or translation text and therefor it would nice to be able to search after them

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-translation-manager/commit/8fab58c3da7a5ebc9a858ad4895eedde03ef9f08

Just for the 0.1 (L4.2) but will be in the new version also.

Just a simple modal box to search for a translation or key.
