### ISSUE TITLE
Export to excel

### ISSUE THREAD

**Issue by BojanKogoj** [barryvdh/laravel-translation-manager#100]
I have to constantly send missing translations in excel (maybe not the best way?), they do not have access to translation manager. Should we try to export for excel, with several options of course, such as
- choose groups to export
- only keys with missing translations
- only selected languages
- ...

**Comment by Rjs37** [comment]
Would definitely be useful. At the moment I do this all manually from the database which isn't a problem, but having it as part of the system would be great.

Obviously it does seem a little long-winded to import from the standard files into the database and then export back into files again (csv) (and reverse afterwards), but I find translators find it easier to working with excel/csv files.

**Comment by marufmax** [comment]
I am looking for this feature also
