### ISSUE TITLE
ErrorException in Manager.php line 63: Array to string conversion in Laravel v.5.2.30

### ISSUE THREAD

**Issue by baaskoen** [barryvdh/laravel-translation-manager#104]
I ran these commands today:

>  composer self-update 
>  composer update

And now my translation manager has stopped working. I'm getting the following error when trying to import groups:  

> ErrorException in Manager.php line 63: Array to string conversion

Composer update did an update for Laravel (v.5.2.29 to v.5.2.30).

**Comment by baaskoen** [comment]
Update: I have downgraded back to Laravel v.5.2.29 and now the translation manager works perfectly fine.

**Comment by dexmans** [comment]
Same issue here, downgrading to 5.2.29 fixed the problem for now

**Comment by teymur647** [comment]
just delete or fill 
resource/lang/en/validation.php     'attributes' => [], 
and it works

**Comment by SubodhDahal** [comment]
This issue has been fixed with this pull request: https://github.com/barryvdh/laravel-translation-manager/pull/107
