### ISSUE TITLE
Translation manager on Laravel 5.2.30

### ISSUE THREAD

**Issue by ejeanneaubc** [barryvdh/laravel-translation-manager#105]
Hi !

I have an error when i try to install the app with Composer. I use Laravel 5.2.30.

Have you the same problem ?

> emmanuel$ composer require barryvdh/laravel-translation-manager
> Using version ^0.2.1 for barryvdh/laravel-translation-manager
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for barryvdh/laravel-translation-manager ^0.2.1 -> satisfiable by barryvdh/laravel-translation-manager[v0.2.1].
>     - Conclusion: remove laravel/framework v5.2.30
>     - Conclusion: don't install laravel/framework v5.2.30
>     - barryvdh/laravel-translation-manager v0.2.1 requires illuminate/translation 5.0.x|5.1.x -> satisfiable by illuminate/translation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
> ....

Thank's a lot !

**Comment by sangnguyenplus** [comment]
:+1:

**Comment by drkwolf** [comment]
+

**Comment by AndreasHerss** [comment]
I have the same problem, i solved it using `"barryvdh/laravel-translation-manager": "0.2.x-dev"` for now :)

**Comment by ejeanneaubc** [comment]
Thank's @AndreasHerss but if i follow the [package installation process](https://github.com/barryvdh/laravel-translation-manager#installation) and i can't run all commands lines and the package is not OK when i move migration file and config file manually.

Thank's for your help !

**Comment by yurtesen** [comment]
This is duplicate of issue https://github.com/barryvdh/laravel-translation-manager/issues/90

**Comment by ejeanneaubc** [comment]
It's works like a charm now.
