### ISSUE TITLE
postDelete bug

### ISSUE THREAD

**Issue by thetispro** [barryvdh/laravel-translation-manager#106]
Controller/postDelete should be:

public function postDelete($group, $key, $sub_group = null)
and not
public function postDelete($group, $sub_group = null, $key)

As $sub_group is never used in the function (Unless I missed something), we could write

public function postDelete($group, $key)

hth

**Comment by sangnguyenplus** [comment]
It will be fix when my pull request is merged.
https://github.com/barryvdh/laravel-translation-manager/pull/108

**Comment by ALTELMA** [comment]
Sorry for my mistake. $sub_group require for anyone separate language directory.

Example
dashboard
    - user
frontend
    - user

@sangnguyenplus Thanks for fixed my bug. :+1:
