### ISSUE TITLE
how to add a new key?

### ISSUE THREAD

**Issue by tishma** [barryvdh/laravel-translation-manager#111]
Hi there,

Sry to ask the obvious, but neither laravel doc nor your readme say a thing about what is preferred way to manually add a key to translation file/db.

I'm working on existing app, and translation files are not under source control, so adding a new key there doesn't seem like a good idea.

Some of my keys are dynamically generated, so detection in code (i.e. import) won't work.

Export to excel than import back from excel did not seem to work (do I have to run artisan export?).

Pls help!

Thanks
v.

**Comment by vpratfr** [comment]
The UI has a button to add a new key inside a group. There is currently no other way to add a group than adding a file inside the lang folder and import it into DB.
