### ISSUE TITLE
Support vendor package translations files

### ISSUE THREAD

**Issue by vpratfr** [barryvdh/laravel-translation-manager#112]
Packages publish their language files into `lang/vendor/my-package/<lang_code>`.

Those files are not seen by the import command. And of course, the export command should be able to write them at the right place too.

**Comment by mortenscheel** [comment]
I think the first part is fixed now. I can import vendor language files just fine.
But when I translate them to a locale not originally supported by the vendor, the publish command doesn't create the new lang file (or the folder it should be created in)
