### ISSUE TITLE
Refactor UI files

### ISSUE THREAD

**Issue by vpratfr** [barryvdh/laravel-translation-manager#113]
Currently the package has a single view with everything in there (HTML, JS, CSS, etc.)

When proposing a UI to a client, it is usually nice to include that into their admin panel.

Here are a few suggestions from what it took to refactor your work:
- Use blade syntax (package is meant for Laravel, at least provide a Blade view)
- Use a layout, that way we can replace that with our own very easily
- Split JS into its own partial view
- Split CSS into its own partial view

Here is what I have now on my project. Neatly integrated.

![image](https://cloud.githubusercontent.com/assets/2526465/15775593/0003da42-2983-11e6-9470-76645a220db8.png)

**Comment by ayndev** [comment]
That's what I was looking for. how can i implement this without touching the vendor package code?
I think the view pages should be published just like the log-viewer package

**Comment by filipveschool** [comment]
@vpattr. Would you find iT ok to share your views and code so I can see how you done it please? I am trying THE same thing but cant get iT working. :(

**Comment by vpratfr** [comment]
I just took https://github.com/barryvdh/laravel-translation-manager/blob/master/resources/views/index.php and updated the HTML markup.

**Comment by vpratfr** [comment]
Oh and I think I needed to adjust a few selectors in the JS too.
