### ISSUE TITLE
Use [] syntax for arrays in exported files

### ISSUE THREAD

**Issue by vpratfr** [barryvdh/laravel-translation-manager#115]
Since Laravel 5 now requires a minimum PHP version which allows that syntax, we should get rid of `array(...)` in favor of `[...]`.

Additionally, the opening array should be placed on the same line as the `=>`. i.e.

```
return array (
  'backend' => 
  array (
    'blah' => ...
```

should be formatted as:

```
return [
  'backend' => [
    'blah' => ...
```

Edit: I saw you are using `var_export` afterwards. Maybe an additional step [as suggested on SO](http://stackoverflow.com/questions/24316347/how-to-format-var-export-to-php5-4-array-syntax)?

**Comment by ALTELMA** [comment]
+1

**Comment by Chalkin** [comment]
Plus one here

**Comment by sineld** [comment]
+1

**Comment by gjm** [comment]
Maybe using [brick/varexporter](https://github.com/brick/varexporter) instead of `var_export()`?
