### ISSUE TITLE
Function inside translation array

### ISSUE THREAD

**Issue by HilmanAnshori** [barryvdh/laravel-translation-manager#127]
Hello,
is it possible to keep function inside language array? 

for example i have : 
`'resend' => 'Your account is not confirmed. Please click the confirmation link in your e-mail, or <a href="' . route('account.confirm.resend', ':user_id') . '">click here</a> to resend the confirmation e-mail.',`

and when translation groups imported, in web interface shown :
`Your account is not confirmed. Please click the confirmation link in your e-mail, or <a href="http://smartphoneservice.dev/account/confirm/resend/:user_id">click here</a> to resend the confirmation e-mail.`

then when the translations are published, the route function is missing and replaced by text just like in the web interface.

Thank you

**Comment by barryvdh** [comment]
No don't think so.

**Comment by barryvdh** [comment]
You could use a replacement parameter instead.

**Comment by HilmanAnshori** [comment]
ok thanks
