### ISSUE TITLE
findTranslations pattern issue

### ISSUE THREAD

**Issue by ju5tify** [barryvdh/laravel-translation-manager#128]
Hi.

Your search pattern starts with `[^\w|>]` which will not work for a Blade code such as:
`<p>@lang('group.key')</p>`
because `@lang` is placed just after `>` symbol

**Comment by barryvdh** [comment]
Can you provide a PR to fix that?

**Comment by vadimwe** [comment]
@barryvdh Can you please push update? @lang not working now

**Comment by barryvdh** [comment]
Which PR?

**Comment by vadimwe** [comment]
PR?

---
Sincerely yours,
Vadims Sevlakovs

+371 28788788
vadims@sevlakovs.com

**Comment by barryvdh** [comment]
Yeah which update do you need me to push?

**Comment by vadimwe** [comment]
Support of @lang in views

---
Sincerely yours,
Vadims Sevlakovs

+371 28788788
vadims@sevlakovs.com
