### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by abejfehr** [barryvdh/laravel-translation-manager#131]
My website is being served with SSL, but when I visit the translations module all of the form URLs are prefixed with the http:// protocol, so there is mixed content and the web server refuses requests to update translations. 

Is there any place in this package I can configure the protocol so HTTP works?

Thanks in advance!

**Comment by abejfehr** [comment]
Never mind, I'm silly. I just needed to add the following lines in my AppServiceProvider.php:

            URL::forceSchema('https');
            $this->app['request']->server->set('HTTPS', true);

All the URLs are automatically created with https:// now!

**Comment by barryvdh** [comment]
Hmm, it should detect that by itself. You might need to set up some reverse proxy configuration in Symfony.
