### ISSUE TITLE
File creation fails if folder does not exist.

### ISSUE THREAD

**Issue by vpakg** [barryvdh/laravel-translation-manager#134]
If a translation is within a sub-folder (e.g. `/fr/admin`) but if the `admin` folder does not exist, the system fails to create the file.

```
[ErrorException]                                                                                                            
  file_put_contents(/var/www/html/resources/lang/fr/admin/labels.php): failed to open stream: No such file or directory
```

**Comment by ganey** [comment]
I'm getting failures on the normal resources/lang/<lang> folders on 5.3 as they don't exist.

**Comment by ALTELMA** [comment]
That's problem will happened when your directory cannot access.
Try to change permissions for your lang folder before.
It should be work, but not good solution for now.
