### ISSUE TITLE
Duplicate translations

### ISSUE THREAD

**Issue by chrisrickard** [barryvdh/laravel-translation-manager#137]
Hi there,

We have used your plugin on a client site, and somehow have ended up with duplicate translations for the same key.

For example, "help.page.title" is in the DB twice, once as "Help" and the other as "Site help".

However it does not show in the translation manager UI twice - annoyingly the "Site help" is showing on the actual website, however "Help" is shown in the manager UI (so as far as the client is concerned it is simply not updating).

Any ideas on how this could have happened?

**Comment by ALTELMA** [comment]
Do you mean same key and same groups?

**Comment by chrisrickard** [comment]
Correct, somehow same group, same key, different value. Just not sure how it got in there in the first place

**Comment by ALTELMA** [comment]
Sorry for late reply. It's possible to manual fix on database?
I not sure, but normally should not happened like this.

This problem is special case or a lot of your clients?
