### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by MarinaWagih** [barryvdh/laravel-translation-manager#143]
i updated from 2.2 to 2.4 and got this error 
![screenshot from 2016-10-17 17 22 13](https://cloud.githubusercontent.com/assets/7422923/19443836/5b6e8c9e-948e-11e6-8ce7-36b6d92d01ad.png)

**Comment by MarlonEtiene** [comment]
I have the same problem.
Downgrade to version 2.3 to back to work.

**Comment by wyandotte** [comment]
I get the same error with Laravel 5.1, it seems it's already fixed with 05921dff. @barryvdh can you publish these changes to a new version?

**Comment by barryvdh** [comment]
Doen

**Comment by wyandotte** [comment]
I now get an "Unsupported operand types" on [line 31](https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Controller.php#L31). Seems to be the same issue, `pluck` is used directly ([line 27](https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Controller.php#L27)) which doesn't work in Laravel 5.1 as it's a Builder object and not a Collection.

**Comment by zanozik** [comment]
@MarinaWagih Sorry for off-topic, but what do you use to debug laravel code like that on the screenshot?

**Comment by barryvdh** [comment]
That looks like Whoops error handler

**Comment by zanozik** [comment]
@barryvdh, spot on, thank you! will try to plug it into my Laravel 5.3 installation. Who is that genius that decided to cut it from Laravel 5 in favor of current ugly unhelpful debugger, I wonder...

**Comment by barryvdh** [comment]
That's because it gave errors and was more work to integrate.

**Comment by zanozik** [comment]
Didn't know that... Looks and works pretty good on Laravel 5.3 here, liking it so far.
