### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055

### ISSUE THREAD

**Issue by zanozik** [barryvdh/laravel-translation-manager#144]
```
PDOException in PDOConnection.php line 77:
SQLSTATE[42000]: Syntax error or access violation: 1055 'invoices.ltm_translations.id' isn't in GROUP BY (SQL: select * from `ltm_translations` group by `locale`)
```

Clean Laravel 5.3 install, ltm version 2.5. Downgraded to 2.4 - problem vanished.

**Comment by opmvpc** [comment]
Hey!

In config/database.php at "mysql" change :
`'strict' => true,`
to false.
Hope it helps!

**Comment by zanozik** [comment]
@opmvpc, you saved me there :) That fixed the problem right away. I have checked the list of limitation modes applied when `'strict' => true` and found none that is particularly useful to my current project. Thank you!

**Comment by barryvdh** [comment]
Was this caused by #138?

**Comment by zanozik** [comment]
@barryvdh I am pretty sure it is.
If you change
`        $locales = Translation::groupBy('locale')->get()->pluck('locale');
`
to
`        $locales = Translation::groupBy('locale')->pluck('locale');
`
Problem disappears.

**Comment by barryvdh** [comment]
So can we change that to 'get('locale')->pluck('locale');'?

**Comment by zanozik** [comment]
@barryvdh, you mean `get(['locale'])->pluck('locale');`? This is working too, but why are you not just using `$locales = Translation::groupBy('locale')->pluck('locale');`?
[https://laravel.com/api/master/Illuminate/Database/Eloquent/Builder.html#method_pluck](https://laravel.com/api/master/Illuminate/Database/Eloquent/Builder.html#method_pluck)

**Comment by barryvdh** [comment]
Because of L5.1-L5.3 compat, see #138

**Comment by zanozik** [comment]
It should work on 5.2-5.3. Maybe you mean compatibility with 5.0-5.1? Will `get(['locale'])->pluck('locale')` even work in 5.0, anyway?
offtopic: 
Your `Barryvdh\TranslationManager\TranslationServiceProvider` was a brilliant idea. This is not just a helper, it's a **game-changer** in developing of i18n software.

**Comment by gerardnll** [comment]
Hi guys, i've just had this problem with 5.2, had to solve it like zanozik proposes. Is it going to have an oficial fix?

**Comment by anthonyPlexuss** [comment]
@opmvpc Thank you for saving me so much time. I appreciate it.

**Comment by jose16-21** [comment]
me salvaste la vida :)

**Comment by masterboy** [comment]
Saved me, thanks, is there any way we can implement this in strict mode? @opmvpc

**Comment by devdbrandy** [comment]
Thanks a bunch man @opmvpc, it helped fix the error.

**Comment by danilrafiqi** [comment]
1. Open config/database.php
2. Change value strict from true to false

'mysql' => [
    'driver' => 'mysql',
    'host' => env('DB_HOST', '127.0.0.1'),
    'port' => env('DB_PORT', '3306'),
    'database' => env('DB_DATABASE', 'forge'),
    'username' => env('DB_USERNAME', 'forge'),
    'password' => env('DB_PASSWORD', ''),
    'unix_socket' => env('DB_SOCKET', ''),
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => '',
    'strict' => false,
    'engine' => null,
],

3. Save

You can read full in my post => [How to Fix SQLSTATE[42000]: Syntax error or access violation: 1055](http://rafibanget.blogspot.com/2018/05/laravel-56-how-to-fix-sqlstate42000_27.html)

**Comment by chized** [comment]
danilrafiqi Thanks really helped, cos the files was first setup on a Windows PC, but started giving this error when moved to Ubuntu
