### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by nielvrom** [barryvdh/laravel-translation-manager#146]
I'm getting the following error when I try to go to /translations:

`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Unsupported operand types' in vendor/barryvdh/laravel-translation-manager/src/Controller.php:31.`

I've done everything like the manual shows. I'm using Laravel v5.1.45.

**Comment by barryvdh** [comment]
can you debug what both values are? Is something null instead of array? If so, what?
Did you use latest version and/or publish config?

**Comment by nielvrom** [comment]
When I do `dd($groups);`  before the line `$groups = [''=>'Choose a group'] + $groups;` then I get   `"auth"`. 

In my composer.json I have this: `"barryvdh/laravel-translation-manager": "^0.2.5"`

**Comment by tappleby** [comment]
Ran into this today, the laravel 5.1[ `pluck` method](https://github.com/laravel/framework/blob/v5.1.45/src/Illuminate/Database/Eloquent/Builder.php#L261-L274) (deprecated) was an alias for `value`

In 5.2 looks like these methods got repurposed and [have a different signature](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L433-L456).

Upgrading To 5.2.0 From 5.1: 
> Eloquent Base Collections
> 
> The Eloquent collection instance now returns a base Collection (`Illuminate\Support\Collection`) for the following methods: `pluck`, `keys`, `zip`, `collapse`, `flatten`, `flip`.

**Comment by nielvrom** [comment]
And is there a way to fix this with my current setup?

**Comment by barryvdh** [comment]
Can you try the latest dev version? ` "^0.2.5@dev"`

**Comment by alrik11es** [comment]
Having same problem here.
Luck this library is not intended for production environments.
Switching for "^0.2@dev"
Thanks.

**Comment by nielvrom** [comment]
I'm getting the same error exception whit the dev version you suggested.

**Comment by mtx-z** [comment]
Same problem here on Laravel 5.1.

**Comment by RogueSheep-nl** [comment]
I had the same issue. `$groups` is a string and therefore cannot be concatenated with the array.
Cause: the result of ->pluck() has been changed from 5.1 to 5.2 :-( .
If you change line 27 from
`$groups = $groups->pluck('group', 'group');`
to
`$groups = $groups->lists('group', 'group');`
This part works properly again in 5.1

**Comment by RogueSheep-nl** [comment]
Changing  line 27 from
`$groups = $groups->pluck('group', 'group');`
to
`$groups = $groups->get()->pluck('group', 'group');`
Will also work in both 5.1 and 5.3 (probably also 5.0 en 5.2?)
See the pull request: #157

**Comment by teoni** [comment]
Simply use the `lists()` function, so use
`$groups = $groups->lists('group', 'group');`
instead of
`$groups = $groups->pluck('group', 'group');`

**Comment by maksimru** [comment]
lists is deprecated in 5.3 and cause error

**Comment by RogueSheep-nl** [comment]
->lists will break the code in 5.2 and up

**Comment by commandantp** [comment]
The "barryvdh/laravel-translation-manager": "0.2@dev", now works with 5.1.
Thanks.
