### ISSUE TITLE
Does not work if group contains slash

### ISSUE THREAD

**Issue by olelis** [barryvdh/laravel-translation-manager#147]
In our project, we use folders to separate different language files

we have such structure:
customer
customer/profile
customer/auth
...

admin
admin/profile
admin/auth

etc

However, such subfolders is not possible to edit, because package generates such url:
http://server/translations/view/customer/profile
=> error 404 as route is defined as translations/view/{group?}  

This can be solved by modifying route parameters like that:

```
$router->get('view/{group?}', 'Controller@getView')->where('group', '(.*)');
            $router->get('/{group?}', 'Controller@getIndex')->where('group', '(.*)');
            $router->post('/add/{group}', 'Controller@postAdd')->where('group', '(.*)');
            $router->post('/edit/{group}', 'Controller@postEdit')->where('group', '(.*)');
            $router->post('/delete/{group}/{key}', 'Controller@postDelete')->where('group', '(.*)');
            $router->post('/import', 'Controller@postImport');
            $router->post('/find', 'Controller@postFind');
            $router->post('/publish/{group}', 'Controller@postPublish')->where('group', '(.*)');
```

Please, fix original problem in code, thank you.

**Comment by oliski** [comment]
https://github.com/barryvdh/laravel-translation-manager/pull/142

here it is fixed, please, accept pull request

**Comment by ALTELMA** [comment]
+1 merge #142 to fix this issue.

Cloud you please merge it?

**Comment by barryvdh** [comment]
That is merged, but reverted now in https://github.com/barryvdh/laravel-translation-manager/pull/295
It needs a seperate regex, because it's not compatible with the json translations otherwise.
