### ISSUE TITLE
Error in laravel 5.3.21 after install

### ISSUE THREAD

**Issue by defser** [barryvdh/laravel-translation-manager#148]
Hey @barryvdh,

After installing laravel-translation-manager and editing the config to my needs I get the following error:

    SQLSTATE[42000]: Syntax error or access violation: 1055 'defser_laravel.ltm_translations.id' 
    isn't in GROUP BY (SQL: select * from `ltm_translations` group by `locale`)

**Comment by defser** [comment]
Regarding this problem I found this: 

> SQL92 requires that all columns (except aggregates) in the select clause is part of the group by clause. SQL99 loosens this restriction a bit and states that all columns in the select clause must be functionally dependent of the group by clause. MySQL by default allows for partial group by and this may produce non-deterministic answers

**Comment by barryvdh** [comment]
same as #144
Can you turn of strict mode?

**Comment by barryvdh** [comment]
Was this caused by #138?

**Comment by defser** [comment]
Yes the issue is solved now! I did not see #144, thanks for the fast response!
