### ISSUE TITLE
Translation variables should not be modifiable. 

### ISSUE THREAD

**Issue by vpakg** [barryvdh/laravel-translation-manager#155]
Just a suggestion. Elements containing `:attribute` should not be modifiable. Users can accidently change / translate the variables inside the translation string, breaking the translation logic.

**Comment by barryvdh** [comment]
Good idea, any thought how to do that?

**Comment by keevan** [comment]
Perhaps...
- an additional option which would allow/disallow edits of any amount of  :attribute on entries in the main language (App::getLocale()), 
- and a check to ensure the attribute must be present in the translated string, if it is not the main language set for the app (returning an error message if it is not present)
 
This can be soft checks (JS only) or hard checks (DB queries on the backend)

It might be simpler than trying to juggle html styles to highlight a required :attribute in the translation strings and worry about whether or not the data that is submitted, is what the user entered.

Thoughts?
