### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression

### ISSUE THREAD

**Issue by i-coder** [barryvdh/laravel-translation-manager#158]
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kamal-oil.ltm_translations.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `ltm_translations` group by `locale`) 

$locales = Translation::groupBy('locale')->get()->pluck('locale'); 
//http://joxi.ru/zANp55wSlb9vQm
 
//Work
$locales = Translation::groupBy('locale')->pluck('locale');

**Comment by maksimru** [comment]
better solution: Translation::**select('locale')->**get()->pluck('locale')

error happens because with that option you can't use non aggregated columns in select statement, so you should forcefully define it

**Comment by renandiett** [comment]
@maksimru I'm having a similar trouble here... how to retrieve all the columns from database when using distinct() or groupBy()? I can just retrieve the columns that is set to select() method. :-(
