### ISSUE TITLE
Make package lang files also available for translation

### ISSUE THREAD

**Issue by KuenzelIT** [barryvdh/laravel-translation-manager#159]
Hey,

I have quite some language files in a custom packages directory. How can I include these files with your translation manager?

Thanks for your work!

**Comment by ALTELMA** [comment]
Where is your location of language file?
resources/lang?

**Comment by KuenzelIT** [comment]
They are in packages/NAME/NAME/src/lang

**Comment by ozkankirik** [comment]
same here.
location of language files are:
- resources/lang
- vendor/*publisher*/*package*/resources/lang

This feature is useful especially for translating self written laravel packages.
