### ISSUE TITLE
Don't properly work on L 5.4.13

### ISSUE THREAD

**Issue by evrard-c** [barryvdh/laravel-translation-manager#177]
After updating to L 5.4.13 The translation-manager interface normally opened but after choosing a group to edit translations, keys and translations didn't load. 
Then i returned to L 5.4.11 and everything work again.

Really want to make a PR to solve it but i'm not yet enough skilled to do so..

**Comment by libressltd** [comment]
I have same problem too. please fix it soon

**Comment by underdpt** [comment]
It seems the groups aren't detected from the route, these are the queries after selecting a group:
```sql
select count(*) as aggregate from `ltm_translations` where `group` = '' and `status` = '1'
select * from `ltm_translations` where `group` = '' order by `key` asc 
```

**Comment by underdpt** [comment]
And I can confirm it works on L 5.4.12.

**Comment by barryvdh** [comment]
Any ideas?

**Comment by bstrahija** [comment]
The method getView() in the Controller is not working properly. The group is not fetched from the route via func_get_args().

If you just declare it with: public function getView($group = null)
and remove the func_get_args, it should work

**Comment by vadimwe** [comment]
@bstrahija Thanx, but it solves only view issue. In 5.4.12 not working also publish translations button.

**Comment by libressltd** [comment]
L 5.4.14 also not working. please fix it asap.

**Comment by bstrahija** [comment]
@vadimwe Yeah, it was just a quick fix. Don't really have the time now, but maybe I can whip up a PR during the weekend if this is not fixed.

**Comment by vadimwe** [comment]
@bstrahija please if you can.

**Comment by vadimwe** [comment]
@libressltd did you found any quick fix?

**Comment by bstrahija** [comment]
I just made a PR (#180) so if you could merge this in, would be great.

**Comment by evrard-c** [comment]
Issue solved by [PR#180](https://github.com/barryvdh/laravel-translation-manager/pull/180) from @bstrahija

**Comment by evrard-c** [comment]
Thanks @bstrahija , the [PR #180](https://github.com/barryvdh/laravel-translation-manager/pull/180) for solving the issue works but some dysfunctions persist
Keys and translated strings load again but it's not possible to export translations or to remove keys on the interface.
I think some modifications like what you did on the PR#180 will definitely solve it

**Comment by dsouksavatd** [comment]
I've tried on L5.3 and L.5.4 it working just fine, no issue as well

**Comment by dsouksavatd** [comment]
@evrard-c I found solution for you change line #53 on /vendor/barryvdh/laravel-translation-manager/src/Controller.php from `public function getView()` to `public function getView($group = null)`

the issue is already committed but still waiting to merge to source code

**Comment by evrard-c** [comment]
My bad, i don't know why it didn't work precedently, it's the same fix @bstrahija has provided.
Thanks @dsouksavatd, now everything seems to work right!

**Comment by nam-co** [comment]
Hello, sorry to bother you Barry, Im on the latest Laravel, 5.4.* but all Im getting is the header, when I Choose a group, nothing is loaded and I see the ltm_translations table is full

Can somebody please help me
regards

**Comment by evrard-c** [comment]
This issue is closed 5 days ago, that means it's already solved
Please, read the thread and you will quickly find the solution.

>  change line #53 on /vendor/barryvdh/laravel-translation-manager/src/Controller.php from `public function getView()` to `public function getView($group = null)`

**Comment by vadimwe** [comment]
@evrard-c this solves only 1 issue. Second problem - translations didn't exported to lang files after publish button clicked.

**Comment by bstrahija** [comment]
Hm, this works fine for me. Are you getting any errors?

**Comment by vadimwe** [comment]
No any errors, After publish button click I see Done publishing the translations for group ‘*’!

But no changes in php files

**Comment by vadimwe** [comment]
Solved after latest package update. @barryvdh thank you.
