### ISSUE TITLE
Problem with laravel 5.2

### ISSUE THREAD

**Issue by cent040** [barryvdh/laravel-translation-manager#181]
I am using laravel 5.2 i installed every thing ... but how to access the translation link using URL... i logged in and when i try to access trough URL.. it's redirect to homepage. I try this .. mywebsite.com/translations

can you please help hoe to add in routes and how to access. Thanks

**Comment by evrard-c** [comment]
1st. open the terminal and execute
` $ php artisan vendor:publish --provider="Barryvdh\TranslationManager\ManagerServiceProvider" --tag=config`
2nd. open the config file _config/translation-manager.php_
3rd. on the config file replace this
```
'route' => [
        'prefix' => 'translations',
        'middleware' => 'auth',
    ],
```
by this

```
    'route' => [
        'prefix' => 'translations',
        'middleware' => [
            'web',
            'auth',
        ],
    ],
```
You don't need to create new route on your route.php file 
All these steps are well described on the presentation page of the package

**Comment by cent040** [comment]
thanks for your help. working now .. 👍
