### ISSUE TITLE
Class 'Barryvdh\TranslationManager\Models\DB' not found

### ISSUE THREAD

**Issue by Lakeron** [barryvdh/laravel-translation-manager#182]
When I use scopeSelectDistinctGroup() in Translation Model, it throw this Exception:

Class 'Barryvdh\TranslationManager\Models\DB' not found

Problem is missing namespace DB.

Possible solution is to ad "use DB;" to header or changed all DB with \DB

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by Lakeron** [comment]
I did .. you can find it here -> https://github.com/barryvdh/laravel-translation-manager/pull/183

**Comment by Lakeron** [comment]
Fixed in this commit https://github.com/barryvdh/laravel-translation-manager/commit/b18e9065d55a9b37e2f689cd35a0963dea4e944b
