### ISSUE TITLE
Cannot see group translations when I choose a group

### ISSUE THREAD

**Issue by janokary** [barryvdh/laravel-translation-manager#184]
Possible problem:

In the ServiceProvider here:

> vendor/barryvdh/laravel-translation-manager/src/ManagerServiceProvider.php

in line 81, we have:
`$router->get('view/{group?}', 'Controller@getView');`
so here:
>vendor/barryvdh/laravel-translation-manager/src/Controller.php

in line 53

`   public function getView()
   {
       $groups = func_get_args();
       $group = implode('/', $groups);
       return $this->getIndex($group);
   }
 `
Shouldn't this be:
`public function getView($group= null)` 

I have 
Laravel v5.4 and
barryvdh/laravel-translation-manager v0.2.7

**Comment by janokary** [comment]
Just noticed that this is fixed after the last release
https://github.com/barryvdh/laravel-translation-manager/commit/4d91fce088f133e2465e62e56d1066e26fd886d3#diff-3840aae95575d417f513143775141e9d
So I upgraded to
dev-master b18e906

**Comment by barryvdh** [comment]
Tagged a new release
