### ISSUE TITLE
The find method not work when the translations files is in subdirectories

### ISSUE THREAD

**Issue by MarlonEtiene** [barryvdh/laravel-translation-manager#185]
Hello,
First thank you for this greate package, it is really awesome!

I got a small trouble, I don't know if it is a real problem or if it is my problem, I use the translation in subdirectories same as:
```
resources
...lang
   ...pt
      ...lessons
         ...hotpotatoes_lesson.php
```
In my files/views sometimes I use
```
{!! Form::label('status_id', trans('lessons/hotpotatoes_lesson.status')) !!}:
```
And the find method not find this `label` status. I made a small change in: vendor/barryvdh/laravel-translation-manager/src/Manager.php at line 107 from `"([.][^\1)]+)+".` to `"([.|\/][^\1)]+)+".` and its worked nice to me.

Dunno if it is a correction, becouse I dunno if it is a problem for anyone or only to me.

Thank you for the attention

**Comment by barryvdh** [comment]
Can you create a pr and update the regexr link /example?

**Comment by MarlonEtiene** [comment]
Yes I can, tomorow I'll do it
