### ISSUE TITLE
Automatic detection

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-translation-manager#192]
I am using Twig with Laravel 5.4 and installed this package. As suggested by mmodler I am able to fetch translations from database by using
`{{ __('lang.key') }}`

But my question is - what syntax should i use in my templates so translator can detect it and put to db with
`php artisan translations:find`

if i use
`{{ 'My text value here' }}`

It does not detect it as translatable string..
Any guide?

**Comment by barryvdh** [comment]
`{{ trans('sdfsdf.fdsdf`) }}

**Comment by octolit** [comment]
This is the same as
`{{ __('lang.key') }}`

It does not save **the value** to database. Entry appears in database without value

| Group     | Key    | Value |
| --------|---------|-------|
| lang  | key   | NULL    |

How do i display the text along with group and key? Should be some syntax such as
`{{ __('lang.key', 'Text to display') }}`

**Comment by barryvdh** [comment]
It does not save the Text to display, it only finds and saves the keys.

**Comment by endytc** [comment]
I think should be able to handle this case
{
     "I love programming."Aku suka permrograman"
}
