### ISSUE TITLE
Laravel 5.3 | Call to undefined method pluck()

### ISSUE THREAD

**Issue by OnArs** [barryvdh/laravel-translation-manager#196]
Hi there!

There is no pluck() in Laravel 5.3 but there is an lists() method available in LTM works properly with it.

`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::pluck()' in /vendor/barryvdh/laravel-translation-manager/src/Controller.php:64`

The same issue in #27 string of `/src/Controller.php` file.

**Comment by luiscordero29** [comment]
Hi, this error for

Field::whereIn('field_id', $data['field_id'])->get()-pluck('group_id');

Solvent

Field::whereIn('field_id', $data['field_id'])->get()->pluck('group_id');
