### ISSUE TITLE
artisan translation:find is not adding new keys

### ISSUE THREAD

**Issue by andrechalom** [barryvdh/laravel-translation-manager#197]
I have been able to import the existing translation keys to the translation-manager and export them back, and it works great. 

However, when I use "php artisan translation:find", it shows the message `Done importing, processed 10 items!`, but these keys are not added to the database. If I run the same command again, the exact same message is displayed. 

Using Linux, Laravel 5.4, my keys are in format `@lang('messages.email')`

I don't have any group listed as `exclude_groups`.

**Comment by tomaszbrunarski** [comment]
I noticed a similar thing, the problem only occured when the html was not formatted. The find function skips the <any tag>@lang due to the first row in the $pattern at Manager.php line 101. Not sure why this is. 
line 101:    "[^\w|>]".                          // Must not have an alphanum or _ or > before real method
Quick workaround is to add a whitespace between > and @. @barryvdh  why does the command skip "@lang" calls which are preceded by ">"?

**Comment by barryvdh** [comment]
Not sure, but I'd be happy to accept a PR for more reliable regex

**Comment by tomaszbrunarski** [comment]
The fix is easy but this line was added deliberately, so I assume that removing this might cause some other problems. I can see with git that @uusa35 commited this last year. Maybe you can shed some light on this issue and why does the command skip the >@lang.

**Comment by tomaszbrunarski** [comment]
Ok I think I get this now. The author did not take under consideration the fact that the @ functions may be requested within the HTML. Thus I would consider doing 2 groups of functions. 1 would be for php embedded code and the other for @ functions. @uusa35 let me know please what you think, if this makes sense I will make a pull request.

**Comment by andrechalom** [comment]
Wow, thanks! As a workaround, I've replaced the `@lang` calls in the files to occupy their own line. If someone is having the same problem, in Vim syntax:
```
:%s/>\s*\(@lang\s*(.*)\)/>\r\1\r/
```

**Comment by andrechalom** [comment]
Digging a bit deeper, this line wasn't changed by @uusa35. It appears so in git blame because of some problem on the history for the branches:

![uusa](https://user-images.githubusercontent.com/1994997/32690745-c92d6b7e-c6e2-11e7-9f95-b7829665574d.png)

The actual change was introduced in PR #102, and makes a lot of sense for the PHP function calls:
> Check: https://regex101.com/r/jS5fX0/2
This little tweak will enhance matching exact methods, so for example the following won't get matched:
  differentMethodtrans('group.key');
  Method1trans('lang.file');
  some_other_method_trans('lang.file');
  $object->trans('lang.line');

Without having two sets of functions, I think there is a way of writing a regex that rejects an arrow notation like "$object->Lang::trans(...", but accepts html tags like "<h1>@lang(..."? I think the only case in which a html tag closes with -> it in .
