### ISSUE TITLE
it's working on laravel 5.4?

### ISSUE THREAD

**Issue by slowas** [barryvdh/laravel-translation-manager#200]
Hello, 

it's working on laravel 5.4?

**Comment by barryvdh** [comment]
Think so

**Comment by FrittenKeeZ** [comment]
It works in 5.4, but 'web' middleware needs to be added.

**Comment by slowas** [comment]
Thx, for information 👍

**Comment by pratik007kumar** [comment]
how to add web middleware

**Comment by farazwebman** [comment]
i have problem with laravel 5.4
import comment response is "Done importing, processed 0 items! Reload this page to refresh the groups!"
this package cant detect my lang files !!!
