### ISSUE TITLE
Find translation in files not working?

### ISSUE THREAD

**Issue by Scarwolf** [barryvdh/laravel-translation-manager#204]
Hey there, I'm using `__("")` to translate things in my entire project. Now the base language is english and there are no _locale_.json files jyet.

I thought "Find translations in files" would find all those `__()` from all the Blade and Controller files but it doesn't. Am I missing something?

**Comment by C-Malet** [comment]
They should be in the `_json` group in the group list.

Have you tried finding these using the command line ?

**Comment by ido567** [comment]
I have the same problem, JSON translations are not imported either by web interface or command line commands.
Laravel version: v5.4.33.
Package version: v0.2.9

**Comment by barryvdh** [comment]
Are you on the latest dev version?

**Comment by ido567** [comment]
No, I used 0.2.9, but now I checked version 0.3 and it worked!
Why version "0.2.x" is specified in the readme?
