### ISSUE TITLE
Giving an error when key is x.y format

### ISSUE THREAD

**Issue by xoco70** [barryvdh/laravel-translation-manager#205]
Hi, 

In one of my translation file, I have:

    'federation' => 'Federación|Federaciones',
    'federation.president' => 'Presidente',
    'federation.vicepresident' => 'Vice Presidente',
    'federation.secretary' => 'Secretario',
    'federation.treasurer' => 'Tesorero',
    'federation.admin' => 'Administrador',
    'federation.address' => 'Dirección',
    'federation.phone' => 'Teléfono',
    'federation.no_user_in_this_country' => 'No hay usuarios registrados en este país',

    'association' => 'Asociación|Asociaciones',
    'association.president' => 'Presidente',
    'association.address' => 'Dirección',
    'association.phone' => 'Teléfono',
    'association.no_user_in_this_country' => 'No hay usuarios registrados en este país',
    'association.add' => 'Agregar Asociación',

When I publish those translation from button, it generates an array:

``` 
'association' => 
  array (
    'president' => 'Presidente',
    'address' => 'Dirección',
    'phone' => 'Teléfono',
    'no_user_in_this_country' => 'No hay usuarios registrados en este país',
    'add' => 'Agregar Asociación',
  ),

``` 
 and it generate an exception:

`explode() expects parameter 2 to be string, array given `

**Comment by rikiless** [comment]
This is still not resolved. Does it mean you cannot use dots in strings used as keys? For example "messages.sign.in" ?

**Comment by JapSeyz** [comment]
@xoco70 Do you have a more detailed stacktrace?

**Comment by xoco70** [comment]
I don't use the plugin anymore:( Sorry!
