### ISSUE TITLE
Console commands not working on 0.4.0

### ISSUE THREAD

**Issue by tfortier** [barryvdh/laravel-translation-manager#209]
Using Laravel 5.5.1 and this package version 0.4.0 every php artisan translations command returns a message similar to this one  : 

```
[ReflectionException]
Method Barryvdh\TranslationManager\Console\ExportCommand::handle() does not exist
```

**Comment by barryvdh** [comment]
Needs to be fire I think

**Comment by tfortier** [comment]
Seems that way yes. This hack did the trick : https://laracasts.com/discuss/channels/laravel/tinkercommandhandle-does-not-exist

**Comment by barryvdh** [comment]
Can you submit a pr to rename?

**Comment by tfortier** [comment]
I guess today is the day I learn how to do a pr :)

**Comment by barryvdh** [comment]
You can just edit via the web interface :)

**Comment by tfortier** [comment]
I think I did a proper pr though it seem my editor is very opinionated when it comes to code styles.
