### ISSUE TITLE
JSON import

### ISSUE THREAD

**Issue by fortael** [barryvdh/laravel-translation-manager#211]
I even don't know if this package supports new 5.4 json format for translations. But the fact is that command from readme don't work.

`php artisan translations:import --json`

```
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--json" option does not exist.                     
                                                          
```

**Comment by JapSeyz** [comment]
@fortael You can simply run `php artisan translations:import` and it will import the JSON too, no need for the --json flag.
