### ISSUE TITLE
Laravel 5.5 console issue

### ISSUE THREAD

**Issue by mbouclas** [barryvdh/laravel-translation-manager#212]
[In 5.5 the fire command needs to be renamed to handle.](https://laravel.com/docs/5.5/upgrade) 
```
Any fire methods present on your Artisan commands should be renamed to handle.
```

I suppose we could be backward compatible by creating a reference to `fire` so that older versions don't break. 
Something like 
```
public function handle() 
{
   $this->fire();
}
``` 

Needs testing of course

**Comment by barryvdh** [comment]
Should be fixed with #210 (tagged now)
