### ISSUE TITLE
Undefined property: Barryvdh\TranslationManager\Translator::$manager [package version 0.4.x]

### ISSUE THREAD

**Issue by andrechalom** [barryvdh/laravel-translation-manager#214]
I've recently upgraded a project from using Laravel 5.4 and laravel-translation-manager 0.2.* to using Laravel 5.5 and laravel-translation-manager 0.4.1, and I started getting the above error from this line: 
https://github.com/barryvdh/laravel-translation-manager/blob/c9939e6199e92d36301143f37a735fcf36d022f5/src/Translator.php#L42

I'm a bit confused as to what's causing this error to appear, and specially why this problem didn't show up before. Also, I've never used the `setTranslationManager` function. However, I've managed to get things working by adding a `protected $manager = null;` to the Translator class. Is this property supposed to be inherited from Illuminate\Translation\Translator?

[ EDIT: upgraded Laravel to 5.5! ]

**Comment by mbouclas** [comment]
Setting the protected property $manager does silence the error, but the translator doesn't work. From what i could tell, the package is not initialized properly as the `$manager` property is set in the `setTranslationManager` method, which is invoked in `TranslationServiceProvider` but the invocation never happens as the following check is falsey
```
            if($app->bound('translation-manager')){
                $trans->setTranslationManager($app['translation-manager']);
            }
```

I hope this will resolved quickly cause it's a bit of a problem

**Comment by andrechalom** [comment]
Right! This is related to the new Laravel auto-discovery feature. Laravel now allows the package maintainers to specify the Service Providers and Facades in the composer.json, and this library is exposing the `TranslationServiceProvider` in its composer.json - but it also depends on a `ManagerServiceProvider`, which is not listed in the composer.json.

Quickfix: add 
```php
        Barryvdh\TranslationManager\ManagerServiceProvider::class,
```

To your config/app.php. 

Probably a permanent fix (untested!): add
```json
        "Barryvdh\\TranslationManager\\ManagerServiceProvider"
```

To the package's composer.json.

**Comment by mbouclas** [comment]
The quick fix doesn't work for me. I had a 5.4 installation which had that provider already, but since going to 5.5 it stopped working.

**Comment by elcobvg** [comment]
Ran into the same problem, but got it working now by also adding the `TranslationServiceProvider` to config/app/php:

`    Barryvdh\TranslationManager\TranslationServiceProvider::class,`

**Comment by mbouclas** [comment]
@elcobvg That still doesn't work for me, keeps crashing.

**Comment by elcobvg** [comment]
@mbouclas what error are you getting?

**Comment by mbouclas** [comment]
`Undefined property: Barryvdh\TranslationManager\Translator::$manager (View: /mnt/hgfs/Work/gala-style/resources/views/home.blade.php)`
`in Translator.php (line 42)`

The error only stops showing up if i add that protected property in `Translator` but it doesn't translate anything. Note, this is in existing projects, not clean 5.5 installations and the service providers are declare in a package, not in `app.php`, although i have tried moving the registration in `app.php` with no luck.

**Comment by kikoseijo** [comment]
Exact same problem here, 
What would be ideal its to be able to just load this library under development, but seems its loads itself no matter what, (this clever laravel engine)

I think a simple .env parameter will allow more flexibility.

BTW: excellent tool, love because if its simplicity. ♥️

**Comment by fortael** [comment]
I have the same problem. Also as it's preloaded by default it always tracking missed translations. 
So i have a big troubles with performance now on some pages. More than 1500 sql requests

**Comment by fortael** [comment]
I found a solution. Just add the following in your `composer.json`

```
    "extra": {
      "laravel": {
          "dont-discover": [
            "barryvdh/laravel-translation-manager"
          ]
      }
    },
```

Then

```
php artisan clear-compiled
php artisan optimize
```
