### ISSUE TITLE
X-editable or contenteditable integration for "Live edit mode"

### ISSUE THREAD

**Issue by sergiorodenas** [barryvdh/laravel-translation-manager#215]
Hello,

How about integrate the translation manager with https://vitalets.github.io/x-editable/ or http://html5doctor.com/the-contenteditable-attribute/ so when the mode is activated and the user has perms is able to edit translations directly from the browser and "on-place".

I've seen this feature on https://www.cs-cart.com/ and it works really nice, @barryvdh have you thought about this before?

I think I can help with PR on this.

Best regards,

**Comment by barryvdh** [comment]
It's already using xeditable

**Comment by Rodenastyle** [comment]
@barryvdh I know but xeditable is on the keys-values page, what I mean is to let the admins change the values directly in the view where it's been using the key, using x-editable and AJAX, just by clicking on the parragraph, button, input, label or maybe on a tooltip near this elements, then a select element fixed on the top to change the language. This way the translation could be done considering the context directly.

**Comment by biwerr** [comment]
Live Editing would be great,.. i've added tried to add a simple live edit function. In most cases it works fine.

I extended the Larvel TranslationProvider and Translator, to add some TranslationPrefix before each translated text. 

```
class ExtendedTranslator extends Translator
{

    public function get($key, array $replace = [], $locale = null, $fallback = true)
    {
        if(config('app.debug')){
            $value = parent::get($key, $replace, $locale, $fallback);

            if(is_string($value))
                return "[[trans:$key]]".parent::get($key, $replace, $locale, $fallback);
        }

        return parent::get($key, $replace, $locale, $fallback);
    }
}
```

Output looks like `[[trans:myfile.mytranslationkey]]this is the translated text` or in HTML

```
<label for="website">[[trans:global.website]]Webseite</label>
```

With Javascript i replace all occurences von [[trans:$key]] and insert a span html tag and set some classes to the parent element.
![ezgif-4-d6453840bbf3](https://user-images.githubusercontent.com/6122710/92252045-ff784580-eecd-11ea-8057-3c234365842a.gif)
