### ISSUE TITLE
Unnecessary exclusion of angle bracket of regex for strings in "find" command

### ISSUE THREAD

**Issue by airtwister** [barryvdh/laravel-translation-manager#223]
I cannot use "find" command for strings like `<b>@lang('messages.some_string')</b>`, because of regex in `findTranslations()` method of `Manager.php`:
```php   
"[^\w|>]". // Must not have an alphanum or _ or > before real method
```

This pattern excludes ">" from search results. 
What is the exclusion for? I can remove these rules from regex and create a PR, if rules are trully unnecessary.

**Comment by andrechalom** [comment]
This is already reported in #197 and some older issues, but it seems that this was explicilty commited by @uusa35. Ping @tomaszbrunarski.
