### ISSUE TITLE
Create locale directory if not exist

### ISSUE THREAD

**Issue by wesamly** [barryvdh/laravel-translation-manager#228]
Hello,
I've used [Find translations in files] and imported group/key correctly for Ar and En locales. The ar locale directory was not created yet. when I exported the group I got the following error:
file_put_contents(PROJECT_DIR/resources/lang/ar/core.php): failed to open stream: No such file or directory

When I mkdir resources/lang/ar the file exported without issues.

Please make it check for directory and create it if not exist.

Thank you for the great package :)

**Comment by mknooihuisen** [comment]
@wesamly This issue appears to have been fixed in a recent commit (#229), which should show up in the next release.  For now, adjust your composer.json to use "dev-master" as the version for this package to get it early.

In `composer.json`

````
"require": {
    ....
    "barryvdh/laravel-translation-manager": "dev-master",
    ....
},
````
