### ISSUE TITLE
Problem with Laravel 5

### ISSUE THREAD

**Issue by gilvaju** [barryvdh/laravel-translation-manager#23]
![captura de tela 2014-11-22 as 16 41 20](https://cloud.githubusercontent.com/assets/677039/5155420/6879c5bc-7266-11e4-8076-1387caffd9d1.png)

How can I fix ?

**Comment by UnrulyNatives** [comment]
I have exactly the same errors:

- the controller is not created. Maybe as a workaround its content should be put into readme.md?

- same with the config file. It does not appear in the expected place as /config/translation-manager.php

Thx

**Comment by barryvdh** [comment]
See #31
