### ISSUE TITLE
Laravel 5.5 /translations redirects to /login

### ISSUE THREAD

**Issue by ToeiRei** [barryvdh/laravel-translation-manager#238]
Route Config as in the documentation, as follows:

```
'route' => [
        'prefix' => 'translations',
        'middleware' => [
	        'web',
	        'auth',
		],
    ],
```

**Comment by Joucke** [comment]
@ToeiRei are you sure you have web listed _before_ auth?

I simply added web to auth (yes, as array) and reproduced your problem, then switched them around and it worked.

**Comment by Victoor** [comment]
Same error here. It's seem that in the middleware Auth::user() returns null

**Comment by Zugmaschine** [comment]
Delete the "auth" from the array, the u can use it without authentication.

**Comment by mohamedsml** [comment]
try to clear caches:

https://itsolutionstuff.com/post/laravel-5-clear-cache-from-route-view-config-and-all-cache-data-from-applicationexample.html

**Comment by albertovincenzi** [comment]
Laravel 5.8: having the same issue. I removed auth and cleared cache. No way. I'm always redirected to login route

**Comment by ToeiRei** [comment]
gave up.

**Comment by mvehar** [comment]
Fix with:
https://github.com/barryvdh/laravel-translation-manager/issues/219#issuecomment-447791453

Clearing config cache
