### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Donny5300** [barryvdh/laravel-translation-manager#24]
- Add Language package trough webinterface
- Change language string while on the website (you can check Drupal 7, string translation module, then you know what i mean)
- Create translation groups in the interface instead of the lang folder

**Comment by janisbarons** [comment]
I would like to see ability to change translation manager language and/or editing layout file, so I could better integrate it with my backend. Basically I have two language backend, but translation manager is only in english.

**Comment by basdog22** [comment]
The filtering is easily done if you use datatables! 
Thanks for another awesome tool!!!

![2015-05-02 17 02 51](https://cloud.githubusercontent.com/assets/132303/7441348/1be8cdaa-f0ed-11e4-9787-33f7d6d5613b.png)
