### ISSUE TITLE
Make it ready for Laravel 5.6

### ISSUE THREAD

**Issue by schmidtflo** [barryvdh/laravel-translation-manager#241]
Laravel 5.6 is out, but the translation manager isn't ready yet.

I don't see any huge changes from Laravel 5.6 that would break it, so it should be easily possible...

**Comment by barryvdh** [comment]
Sure, make a PR

**Comment by kirapwn** [comment]
The PR is already merged for 5.6, could you do a release?

**Comment by nasirkhan** [comment]
is there any expected release date?

**Comment by oleksiyPetlyuk** [comment]
Any updates?

**Comment by decaluwepatrick** [comment]
I would need it as well :)
