### ISSUE TITLE
Delete not working: wrong check in controller

### ISSUE THREAD

**Issue by 9livesdevelopment** [barryvdh/laravel-translation-manager#25]
Hi,

The check in the function postDelete in controller.php line 95 should be:

if(!in_array($group, $this->manager->getConfig('exclude_groups')) && $this->manager->getConfig('delete_enabled')) {

instead of

if(!in_array($group, $this->manager->getConfig('exclude_groups')) && !$this->manager->getConfig('delete_enabled')) {

Notice the ! before $this->manager->getConfig('delete_enabled') that shouldn't be there.

**Comment by barryvdh** [comment]
Fixed in https://github.com/barryvdh/laravel-translation-manager/commit/63bc6a4e231dc53f3b4609247c0a24861935c786

Better now?
/cc @frzsombor

**Comment by frzsombor** [comment]
Oops, you are right.
Now I feel really bad, sorry!
