### ISSUE TITLE
L5.6 support

### ISSUE THREAD

**Issue by gwleuverink** [barryvdh/laravel-translation-manager#250]
Hi! I see PR's to accommodate for Laravel 5.6 are merged with master already. Any idea when a new release will be tagged? I need to upgrade one of my projects but feel a bit iffy ignoring my minimum stability settings in production.
Thanks!

**Comment by maorkavod** [comment]
I am also waiting for Laravel 5.6 support, are you upgrade your package for this in the nearest future?

**Comment by crlcu** [comment]
Any idea when the new tag will be created?

**Comment by przemekperon** [comment]
@barryvdh could you make a new release with support for Laravel 5.6.

**Comment by Marcuzz** [comment]
Use `dev-master` as the version until the tag is created

**Comment by llioor** [comment]
@Marcuzz I have this issue when I run composer update:
`Package is not installed: barryvdh/laravel-translation-manager-9999999-dev`

**Comment by maorkavod** [comment]
Remove the package.
Than install the dev-mastet branch. Use the tag name.

**Comment by nasirkhan** [comment]
getting an error while tried to upgrade my laravel version to 5.6. any workaround till the next release?

**Comment by maorkavod** [comment]
@nasirkhan 

first comment this lines in /config/app.php

Barryvdh\TranslationManager\ManagerServiceProvider::class,
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

this remove the package "barryvdh/laravel-translation-manager" 
from composer, than update composer.  now add this line to composer instead : 

  "barryvdh/laravel-translation-manager": "dev-master"
 
now update composer, than uncomment back the lines from /config/app.php

Barryvdh\TranslationManager\ManagerServiceProvider::class,
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

**Comment by rikiless** [comment]
Works well with [v0.5.0](https://github.com/barryvdh/laravel-translation-manager/releases/tag/v0.5.0) (Laravel 5.6.38). The issue should be closed.
