### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by Light-Studio** [barryvdh/laravel-translation-manager#251]
Hi, I'm on Laravel 5.5 and i'm trying to import my translation file in the manager, they are .php file in resources/lang/en and resources/lang/fr. So I tried to use:
`$ php artisan translations:import`

but i get : Done importing, processed 0 items!

then I tried : 
` php artisan translations:find`
and it found some entry but juste the english one and the key, the value of the key and the french translation are not there :/

What should I do ? thanks for your help !

**Comment by Light-Studio** [comment]
Finally I used the fork form HighSolution ! work great with laravel 5.5
https://github.com/highsolutions/laravel-translation-manager

**Comment by CristianH033** [comment]
I have the same problem with Laravel 5.5 and laravel-translation-manager 0.4.2, I had to switch to version 0.4.1 to import the translations.

**Comment by pxinvoice** [comment]
no resolution?
