### ISSUE TITLE
Missing required parameters for [Route: ] [URI: translations/delete/{groupKey}/{translationKey}].

### ISSUE THREAD

**Issue by robertnicjoo** [barryvdh/laravel-translation-manager#254]
why do i get this error on fresh install?

```
Missing required parameters for [Route: ] [URI: admin/translations/delete/{groupKey}/{translationKey}].
```

**Comment by wimurk** [comment]
This happends when you install it on laravel 5.6 Got the same error after upgrading. And not even this alone. Alsto these errors show up 

`Action Vsch\TranslationManager\Controller@getInterfaceLocale not defined.`

**Comment by bighiu** [comment]
One temporary easy fix is to disable Delete action on **resources/views/vendor/translation-manager/index.php** for routes (the problem I think is related with the curly brackets on translation key)

Line ~525:
Replace `<?php if ($deleteEnabled): ?>`
With `<?php if ($deleteEnabled && $group != 'routes'): ?>`

**Comment by BassemN** [comment]
This PR #301 should fix this issue.

**Comment by rabol** [comment]
Just got this:

I have an existing project, installed according to the guide, selected the _json group and got the error
I have a (for what ever reason) vendor/wireui group, and when I select that, I do not get the error.
