### ISSUE TITLE
I get this error: Call to undefined method [package]

### ISSUE THREAD

**Issue by UnrulyNatives** [barryvdh/laravel-translation-manager#26]
I get the error after I install the package.
Any way to solve it?

**Comment by barryvdh** [comment]
Can you try `0.2.x@dev` ?

**Comment by UnrulyNatives** [comment]
It helped. Thank you!

**Comment by barryvdh** [comment]
Okay but still need to change a bit, regarding the route registering etc. Not sure, are you also getting `Call to a member function domain() on a non-object` on `/translations` using the last commit? (https://github.com/barryvdh/laravel-translation-manager/commit/5403cf3c5429b21b63647684f5c2734760d266d6)

**Comment by UnrulyNatives** [comment]
Not yet - I need a minute to get that far

**Comment by barryvdh** [comment]
Fixed, otherwise #31
