### ISSUE TITLE
Error when version dev-master (^0.4.2)

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [barryvdh/laravel-translation-manager#262]
Symfony\Component\Debug\Exception\FatalThrowableError  : Parse error: syntax error, unexpected 'public' (T_PUBLIC)

  at /var/www/cf/vendor/barryvdh/laravel-translation-manager/src/Manager.php:314

**Comment by barryvdh** [comment]
Can you submit a pr?

**Comment by nguyenphuocnhatthanh** [comment]
@barryvdh 
I created PR
https://github.com/barryvdh/laravel-translation-manager/pull/263
Pls check it.
