### ISSUE TITLE
Bug with @lang

### ISSUE THREAD

**Issue by YordanovBg** [barryvdh/laravel-translation-manager#269]
Hi,
we are using this package and we found a bug with the "$stringPattern" regex for the @lang directive inside "findTranslations" method
-If the file starts with @lang 
-If @lang is immediately after an html tag (no spacing before)

You can see links below:
https://regex101.com/r/Kmz52y/1
https://regex101.com/r/crVgZD/1

https://regex101.com/r/FRV8ou/1 - works here

Thank You

**Comment by hadavand** [comment]
Hi, I also faced with this problem

**Comment by sipy** [comment]
Me, too, the `findTranslations` method does not find all the strings in files with `@lang` function, especially those with the `>` character immediately before the `@lang` function...

**Comment by davidajnered** [comment]
Removing `"[^\w|>]"` from the regex in Manager.php (line 161 and 173) solved the problem with `@lang` directly after a `>`. Tested it on one of my projects and it works, but I guess there is a reason why that line exists. `// Must not have an alphanum or _ or > before real method` doesn't explain enough so more info would be needed before working on a PR.

**Comment by wimurk** [comment]
Got the same problem. Also with the new laravel 5.7

**Comment by royduin** [comment]
Same issue here, with another example: https://regex101.com/r/WEJqdL/2, can you explain why the regex starts with `[^\w|>]` @barryvdh as asked by here: https://github.com/barryvdh/laravel-translation-manager/issues/269#issuecomment-403270709

**Comment by barryvdh** [comment]
Submit a PR and I will merge it.

**Comment by barryvdh** [comment]
This was meant to prevent false positives, see https://github.com/barryvdh/laravel-translation-manager/pull/102

Not sure why the `>` was there though. Maybe @themsaid  remembers?

**Comment by royduin** [comment]
As @barryvdh just pointed out, why don't we want `$object->trans('lang.line');`? `lang.line` is also a key we want right?

**Comment by barryvdh** [comment]
Yeah see https://regex101.com/r/WEJqdL/6

**Comment by barryvdh** [comment]
Fixed with https://github.com/barryvdh/laravel-translation-manager/pull/290

**Comment by barryvdh** [comment]
Oh still leaves the start of file issue.

**Comment by royduin** [comment]
Jup, but is that really an issue @YordanovBg? I don't have or know any projects with template files which start with a translation?

**Comment by sipy** [comment]
@royduin I think it is not a "real world issue" but it should work as expected. Me and @YordanovBg finally decided to use this library: [https://github.com/kkomelin/laravel-translatable-string-exporter](url) that does not have these issues and it is much, much faster as well. Maybe this plugin (laravel-translation-manager) could use it internally as well.

**Comment by royduin** [comment]
@sipy, the link in your comment doesn't work, so hereby the right link: https://github.com/kkomelin/laravel-translatable-string-exporter (or you should have copy pasted it). I've looked at that package but that one has false positives as fixed by @themsaid in this package here: https://github.com/barryvdh/laravel-translation-manager/pull/102. Further it's almost the same how it functions. I want the interface so my customer can use it to translate instead of giving them a json file.

**Comment by barryvdh** [comment]
I think the performance drop might be because the resources locations have changed. Used to be `app/views` etc, but currently are different. So I'm not sure if it searches the vendor folder now. We should probably change it to just `app` and `resources`, or skip `vendor`
See https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Manager.php#L183

**Comment by royduin** [comment]
@barryvdh, I can confirm it's scanning everything because the command doesn't set a path so the base path will be used.

**Comment by barryvdh** [comment]
Okay you can try with https://github.com/barryvdh/laravel-translation-manager/commit/8a72e9f857c7e4366cd04a2f3e7134c36703e82b

**Comment by sipy** [comment]
@royduin, yes the link was wrong, I've updated it, sorry for that :). Sure, I totally agree about the user interface, that's why I've suggested to use the library I linked only for the searching under the hood ("...use it internally...").

**Comment by sipy** [comment]
It would be nice to let the programmer chose what folders to scan, like the library I've linked (https://github.com/kkomelin/laravel-translatable-string-exporter/blob/master/config/laravel-translatable-string-exporter.php).

**Comment by royduin** [comment]
> Okay you can try with [8a72e9f](https://github.com/barryvdh/laravel-translation-manager/commit/8a72e9f857c7e4366cd04a2f3e7134c36703e82b)

I don't see the problem of scanning the vendor dir. It could be possible there are translations there I want. For example in blade files shipped with a package I haven't published. And performance... nah, yes for sure it could be faster but how often do we run a scan? It doesn't take more then 10 seconds.

**Comment by royduin** [comment]
> It would be nice to let the programmer chose what folders to scan, like the library I've linked (https://github.com/kkomelin/laravel-translatable-string-exporter/blob/master/config/laravel-translatable-string-exporter.php).

Maybe this is a nice addition indeed.
