### ISSUE TITLE
MySQL reserved keywords

### ISSUE THREAD

**Issue by UnrulyNatives** [barryvdh/laravel-translation-manager#27]
I get this: 

The column name 'group' is a MySQL reserved keyword.
The column name 'key' is a MySQL reserved keyword.

Maybe the column names should be changed?

**Comment by barryvdh** [comment]
Hmm probably. Never got that issue. Are you in strict mode?

**Comment by UnrulyNatives** [comment]
Hmm probably. :)

I checked. Yes. I was in strict mode
