### ISSUE TITLE
Question - how to handle git?

### ISSUE THREAD

**Issue by kklon** [barryvdh/laravel-translation-manager#276]
hey,
I've started using this package recently, but I can't work out how to handle tracking files for translations in git. As this package needs to both write into them in production, as well as to catch up on new entries, I obviously can't add those directories to gitignore.
How do others handle it? 
Only thing I can think of is to add alter my deployment procedure and add a git commit on my server before updating. I'm using forge.
Any suggestions more than welcome

**Comment by ikerasLT** [comment]
I'm doing

```
php artisan translations:import
php artisan translations:export \*
```

On production so the new translations is added but changes aren't overwritten.

**Comment by Hesesses** [comment]
> I'm doing
> 
> ```
> php artisan translations:import
> php artisan translations:export \*
> ```
> 
> On production so the new translations is added but changes aren't overwritten.

Hello,

I tried to add these lines end of the forge deploy scripts, but getting conflict when merging language files.

I dont understand how this could work when you edit translations on server and then new translations should be pushed... which results always a conflict?
