### ISSUE TITLE
\Lang::has() should not trigger TranslationManager missingKey()

### ISSUE THREAD

**Issue by zanozik** [barryvdh/laravel-translation-manager#285]
When using `Barryvdh\TranslationManager\TranslationServiceProvider::class` for fishing out missing translations you will get unwanted strings to your database through usage of `\Lang::has()` method, which is kind of defying the whole `\Lang::has()` idea.
Translation manager will not import these strings to your files, if they are left empty, and that's a good thing, although, you will have to remember these strings to not translate it, and, if you are working in a team, as many of us do, you will have no control whatsoever on what's gets translated and that will brake your application, since  `\Lang::has()` will return `true`.

**Comment by zanozik** [comment]
No one responded to this issue created 1.5 years ago... Is the package not maintained / abandoned?

**Comment by barryvdh** [comment]
I'm not sure what makes most sense, add them or not.
