### ISSUE TITLE
Doesn't find all strings from Lang.php files

### ISSUE THREAD

**Issue by GeoSot** [barryvdh/laravel-translation-manager#287]
Hello, after the last update, when I run the command `php artisan translations:import` to insert lang stings in Db, I get only some of them . 

 I can't find any logical pattern. In other cases it reads the whole file, in other, only a limited number of  strings from the file.

Has anything changed?

**Comment by barryvdh** [comment]
Is this fixed with https://github.com/barryvdh/laravel-translation-manager/pull/290 ?

**Comment by GeoSot** [comment]
Unfortunately not. If it helps, I found out that this glitch appears only in windows systems
