### ISSUE TITLE
no view files when choosing a group to display the group translations

### ISSUE THREAD

**Issue by UnrulyNatives** [barryvdh/laravel-translation-manager#29]
After successfuly starting yhe web panel, I find translations and groups, then, when trying to display translations from a group, such as 
translations/view/messages
translations/view/pagination

I get 404.

I use this starter project: 
https://github.com/bestmomo/laravel5-example

**Comment by barryvdh** [comment]
Closing if favor of #31 
There have been more changes last hour.
