### ISSUE TITLE
Undefined variable: group

### ISSUE THREAD

**Issue by rperednikas** [barryvdh/laravel-translation-manager#296]
`echo $group`
This code in webinterface won't understand what to show to view

Im using Laravel 5.7, but this translation manager won't load, i've make all installation step by step by readme file. 

Routes file:

`Route::get('/translations', function(){
	return view('vendor.translation-manager.index');
});
`

**Comment by PinkME77** [comment]
Same issue. Did you find the cure?

**Comment by sergeynew** [comment]
+1
