### ISSUE TITLE
Update bootstrap to 4

### ISSUE THREAD

**Issue by vladyslavstartsev** [barryvdh/laravel-translation-manager#298]
it will be nice if the main template will be updated to v4 of bootstrap

**Comment by KalimeroMK** [comment]
Create the pr for with update code but you can use my upload 
https://packagist.org/packages/kalimeromk/laravel-translation-manager

**Comment by vladyslavstartsev** [comment]
@KalimeroMK it is better not to create yet another package.
See https://packagist.org/packages/submit under "Do not submit forks of existing packages".

It is better to just rely on repository.

And wait/help review and help with merge of your PR

**Comment by KalimeroMK** [comment]
> @KalimeroMK it is better not to create yet another package.
> See https://packagist.org/packages/submit under "Do not submit forks of existing packages".
> 
> It is better to just rely on repository.
> 
> And wait/help review and help with merge of your PR

I allready create pr but ....
