### ISSUE TITLE
how to switch between languages?

### ISSUE THREAD

**Issue by techybirds** [barryvdh/laravel-translation-manager#300]
# **first your documentation is not complete.**
 also its not provide any kind of information about how to add different language. btw somehow i added language but how to switch languages. 
for example : 
https://www.mydomain.com/en
https://www.mydomain.com/es
https://www.mydomain.com/pt

or is there any other way?

**Comment by techybirds** [comment]
# **How to manage custom string?**

**Comment by vadimwe** [comment]
You should handle first path segment and use it as locale like app()->setLocale($firstPathSegment). Best way is to do it in RouteProvider or before middleware.
