### ISSUE TITLE
Config `exclude_langs` no longer in use?

### ISSUE THREAD

**Issue by kentdahl** [barryvdh/laravel-translation-manager#302]
The config published includes the `excludes_langs` entry, but I cannot see anywhere it is used. Should this be removed / deprecated?

The same functionality works through `storage/.ignore_locales` file.

**Comment by frkn2076** [comment]
You can use hide option to exclude language like,

> https://github-readme-stats-eight-theta.vercel.app/api/top-langs/?username=frkn2076&langs_count=8&theme=radical&layout=compact&hide=html,css

@kentdahl
