### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by mrahmadt** [barryvdh/laravel-translation-manager#304]
Hello

Is their anyway I can use laravel-translation-manager with lumen framework ?

I’m not able to get it to work, can you help me?

**Comment by 4dk1998** [comment]
> Hello
> 
> Is there any way I can use laravel-translation-manager with lumen framework ?
> 
> I’m not able to get it to work, can you help me?

I have also same issue. Is anyone know this?

**Comment by webkod3r** [comment]
Hi there... any news on this? I have a lumen project i'd like to integrate translations for.

Thanks.
