### ISSUE TITLE
[0.2] Laravel 5 support

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-translation-manager#31]
I think I've got a basic version working for now

Tasks:
 - [x] New way of registering config/views
 - [x] Update app paths
 - [x] Add CSRF protection
 - [x] Change route registering
 - [x] PSR-4
 - [x] Remove deprecated options (Form)
 - [x] ..?

**Comment by UnrulyNatives** [comment]
perfect!
I will test the thing tomorrow.

Thank you again,

Peter

**Comment by UnrulyNatives** [comment]
Unfortunately the thing doesn't work yet. 
Can you declare your plans as of using DB not files in production app?

**Comment by barryvdh** [comment]
No plans yet.

**Comment by markushausammann** [comment]
Interested in this plugin, does it work?

**Comment by barryvdh** [comment]
yes

**Comment by UnrulyNatives** [comment]
As the L5 support is working perfectly (thank you!!), we could close this issue!
