### ISSUE TITLE
Serch inside ServiceProvider lang folders

### ISSUE THREAD

**Issue by fsou** [barryvdh/laravel-translation-manager#310]
Service Providers have the ability to load their own translation files, using `loadTranslationsFrom`

```php
public function boot()
{
    $this->loadTranslationsFrom(__DIR__.'/path/to/translations', 'courier');
}
```

It would be great if the Translation Manager could manage this translations too, using the same syntax for groups, like `courier::file`.

Regards

**Comment by gjm** [comment]
I also need this.
