### ISSUE TITLE
latest commits cause issues

### ISSUE THREAD

**Issue by robbielove** [barryvdh/laravel-translation-manager#317]
When I try to update with composer I get:

`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Tanmuhittin\LaravelGoogleTranslate\LaravelGoogleTranslateServiceProvider' not found`

Commit #311

**Comment by barryvdh** [comment]
Ping @tanmuhittin

**Comment by tanmuhittin** [comment]
I will work on it tonight 😊👍

**Comment by tanmuhittin** [comment]
@robbielove Could you please write the steps to reproduce the error. I tried reproducing via following steps but did not receive any errors:
```
composer require barryvdh/laravel-translation-manager dev-master
composer update
```

**Comment by tanmuhittin** [comment]
@robbielove Could you please share your composer.json and elaborate the problem.

**Comment by robbielove** [comment]
@tanmuhittin thanks for your prompt response, since you suggested posting composer.json - it suggested to me that this is where the problem lies. I ended up replacing all sections after 'require' and  'require-dev' with a copy from a fresh laravel install and the issue went away.

**Comment by ncla** [comment]
Still an issue, upon requiring the package (composer require) I get this error

`Class 'Tanmuhittin\LaravelGoogleTranslate\LaravelGoogleTranslateServiceProvider' not found`

Requiring specific version (last release as of writing) solved it

`composer require barryvdh/laravel-translation-manager:v0.5.3`
