### ISSUE TITLE
publish translations to a sub-site which is a client to an api server. client site doesn't have a db

### ISSUE THREAD

**Issue by alithestar2000** [barryvdh/laravel-translation-manager#319]
Hi everyone,

Our project is structured such that there's a back-end server which has all the api's to communicate with the database. and there are sub-sites which are used by end-users. these sub-sites connect with api server to store or fetch data. we want to make edits to translations on the back-end api server and publish them to both back-end and client site. How can i modify the default behavior because vendor directory is not in git. i cannot make changes directly to vendor directory. also composer update is a problem.

plz help

**Comment by tanmuhittin** [comment]
You can fork, edit and then use it. Check https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository
