### ISSUE TITLE
[0.2] the laravel5.0 lang path changed

### ISSUE THREAD

**Issue by yqmking** [barryvdh/laravel-translation-manager#32]
the lang path has been moved to /resources/lang
but the 

D:/mysite/test/laravel5/vendor/barryvdh/laravel-translation-manager/src/Manager.php:140

$path = $this->app->make('path').'/lang/'.$locale.'/'.$group.'.php';

still use the L4's path.

maybe same problem of  find command

**Comment by barryvdh** [comment]
Should be fixed.
