### ISSUE TITLE
The command "translations:export" does not exist.

### ISSUE THREAD

**Issue by Woutje99** [barryvdh/laravel-translation-manager#320]
It is not possible to do `Artisan::call('translations:export')`, all other commands are working well when calling with the Artisan command.

**Comment by PollieDev** [comment]
Hey! Not sure if this is the best workarround for now.
But I have managed to work this out by using the "exec" command built into PHP for now.

This is what I replaced the artisan call by:
```
exec('cd .. && php artisan translations:export');
```
Haven't fully tested (only on Windows) so not completely sure if it might fuck up on other OS.
Any further improvements are ideas definitely welcome 😄
