### ISSUE TITLE
Unable to export translations inside vendor folder of Lang

### ISSUE THREAD

**Issue by hardik1595** [barryvdh/laravel-translation-manager#322]
![image](https://user-images.githubusercontent.com/25504774/59961368-5590e100-94f4-11e9-803c-3627b7eca63b.png)
it takes extra argument while exporting for vendor files. Any idea how to fix it?
See : **/vendor/backup/en** and **en/vendor/backup.php**
Real path is **lang/vendor/backup/en/notifications.php**
Thanks in advance

**Comment by danicm93** [comment]
I have the same problem

**Comment by sjoy** [comment]
me too

**Comment by MichaelAben** [comment]
same for me, the url is wrong:
resources/lang/vendor/MabenDevTwoFactor/en/en/vendor/MabenDevTwoFactor.php

**Comment by hoRacy** [comment]
I have the same problem.

**Comment by martinschenk** [comment]
same for me
