### ISSUE TITLE
Call to undefined function Barryvdh\TranslationManager\array_dot()

### ISSUE THREAD

**Issue by ravindrasinghinbox** [barryvdh/laravel-translation-manager#332]
C:\xampp\htdocs\blog>php artisan translations:import
     99|                 if ( $translations && is_array( $translations ) ) {
  > 100|                     foreach ( array_dot( $translations ) as $key => $value ) {
    101|                         $importedTranslation = $this->importTranslation( $key, $value, $locale, $group, $replace );
    102|                         $counter             += $importedTranslation ? 1 : 0;
    103|                     }
    104|                 }

  Exception trace:

  1   Barryvdh\TranslationManager\Manager::importTranslations()
      C:\xampp\htdocs\blog\vendor\barryvdh\laravel-translation-manager\src\Console\ImportCommand.php:40

  2   Barryvdh\TranslationManager\Console\ImportCommand::handle()
      C:\xampp\htdocs\blog\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

**Comment by barryvdh** [comment]
Can you try with the latest version?

**Comment by saschati** [comment]
You need to install the "dev-master" version, there is a fix for this package

**Comment by ilechcod** [comment]
This issue just showed up again on laravel 8.4.1!!! Call to undefined function array_dot() from my ServiceProvider file.

**Comment by barryvdh** [comment]
This needs to be replaced with the Array facade (Array::dot())
