### ISSUE TITLE
After i upgraded to laravel 6 and latest trans manager version.

### ISSUE THREAD

**Issue by emptimd** [barryvdh/laravel-translation-manager#339]
The web interface part doesn't seem to work fine.
It feels like it lacks some js.

1) I can enter the index page
https://ibb.co/Bc98vzw
But when i choose a group it dosent throw me to the view page. It dose nothing.

2)I can manually go to the view page of the group.
https://ibb.co/yFmMF62
But when i press on any translation and expect to get the popup, in the url i get the '#edit' and no popup. 'admin/translations/view/salesAdmin#edit'

I have no js errors in console, cache cleared. Is this a bug, or why is my version lacking interactions?

Thanks.

**Comment by mafftor** [comment]
Hi. First of all: We don't know what version You are using. What OS?
Have you followed to instructions of installation?
Maybe you have included the jQuery twice?
Unfortunately, lack of information to help
