### ISSUE TITLE
Not all translations detected

### ISSUE THREAD

**Issue by Elkex** [barryvdh/laravel-translation-manager#345]
I recently re-structured all my blade files with strings for translation.

They always have the same structure:

> user-role.templatename.section-description

So the structure of the three parts `group.key.description` should have been respected. However, my application does not seem to find all translations.

Here are a few examples of translatable strings the translation manager does not seem to find:

> super-admin.createorder.cta-add
> super-admin.question-type.question-open

It only seems to find 210 translatable strings, but it should at least be double of them.

Is there anything I have been missing or doing wrong to detect the other strings?

**Comment by barryvdh** [comment]
The regex probably doesn't match on the dashes. Do all missing items have those?

**Comment by Elkex** [comment]
> The regex probably doesn't match on the dashes. Do all missing items have those?

Not all references have dashes, some do.

Some examples of found translation strings:

> admin.credit-cart.amount-description
> admin.edit-user.field-type-admin
> admin.order-confirmation.status
> admin.user.usertest-results

So it it a combination of both, with dashes and without that are being accepted

Could it be there is a problem if the group & key element both have a dash?

**Comment by Elkex** [comment]
The problem has been solved. :-)
