### ISSUE TITLE
Abandoned packages replacement?

### ISSUE THREAD

**Issue by syntafin** [barryvdh/laravel-translation-manager#346]
![Pakete die geändert werden müssen!!!](https://user-images.githubusercontent.com/695535/72198418-3b393900-342d-11ea-9e24-0413d7edfded.png)

Will these packages be replaced?

**Comment by vladyslavstartsev** [comment]
this was not laravel-translation-manager

it was caused by some other package that you installed before

**Comment by syntafin** [comment]
Yeah found out what, did not see the error before.
Caused by Laravel Nova :) Issue closed!
