### ISSUE TITLE
Where can I find tests for the package

### ISSUE THREAD

**Issue by ishendywebdeveloper** [barryvdh/laravel-translation-manager#353]
I can't seem to find tests for the translation package here. Can someone guide me to where I can find them?

**Comment by barryvdh** [comment]
![image](https://user-images.githubusercontent.com/973269/74525176-ce7bf780-4f20-11ea-80da-5182ed8891bf.png)

**Comment by barryvdh** [comment]
But feel free to open a PR to add some tests :)
