### ISSUE TITLE
Problem compatibility Laravel 7

### ISSUE THREAD

**Issue by NicolasKulka** [barryvdh/laravel-translation-manager#357]
When do you plan to go to Laravel 7?

**Comment by NicolasKulka** [comment]
Linked to this package

**Comment by Siddharaj6010** [comment]
@NicolasKulka Did you face any issues with Laravel 7? 

I tried installing it in my Laravel 7 app and it worked just fine. So I want to make sure there are no hidden bugs before using this package. Thanks

**Comment by NicolasKulka** [comment]
No issues.
Everything it's ok.

**Comment by Siddharaj6010** [comment]
In that case you might want to close this issue :)
