### ISSUE TITLE
how to import subfolder files

### ISSUE THREAD

**Issue by The-Hasanov** [barryvdh/laravel-translation-manager#36]
//Imported
button.php
general.php
messages.php
pagination.php
reminders.php
site.php
table.php
validation.php

// Not Imported
admin\html.php
admin\menu.php
admin\blogs\messages.php
admin\blogs\table.php
admin\blogs\title.php
admin\comments\messages.php
admin\comments\table.php
admin\comments\title.php
admin\companies\messages.php
admin\companies\table.php
admin\companies\title.php
admin\roles\messages.php
admin\roles\table.php
admin\roles\title.php
admin\users\messages.php
admin\users\table.php
admin\users\title.php
user\user.php

This problem only to me ?
Laravel 4.2

**Comment by sameerpanjwani** [comment]
I have the same issue on L5, how do you import subfolders

**Comment by ianciu** [comment]
Can someone help with the same issue, please, even idea.

**Comment by oliverpool** [comment]
Fix proposal: #121
