### ISSUE TITLE
feature request - button PUBLISH ALL GROUPS NOW

### ISSUE THREAD

**Issue by UnrulyNatives** [barryvdh/laravel-translation-manager#37]
I will soon ask several people to work on translations - 5 languages with  several files each (routes, messages, etc.).

They are sure to forget to 'publish' from time to time, and I have no way to determine if they did so.
Based on trust in the quality of the translation I want to be able to  PUBLISH ALL GROUPS NOW. 

Can you make such a button, please?

**Comment by barryvdh** [comment]
It is possible to do that with the command line, use '*' as group (with quotes)
but could make a button I guess.
