### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by yazeedayyash1** [barryvdh/laravel-translation-manager#372]
im trying to update to laravel 8 but i get 

Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
    - stichoza/google-translate-php v4.0.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - stichoza/google-translate-php v4.0.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - stichoza/google-translate-php v4.0.2 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - stichoza/google-translate-php v4.1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install barryvdh/laravel-translation-manager v0.5.9|install guzzlehttp/guzzle 6.5.x-dev
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - barryvdh/laravel-translation-manager 0.5.x-dev requires tanmuhittin/laravel-google-translate ^2.0.1 -> satisfiable by tanmuhittin/laravel-google-translate[2.0.1, 2.0.2, 2.0.3].
    - tanmuhittin/laravel-google-translate 2.0.1 requires stichoza/google-translate-php ^4.0 -> satisfiable by stichoza/google-translate-php[v4.0.0, v4.0.1, v4.0.2, v4.1.0].
    - tanmuhittin/laravel-google-translate 2.0.2 requires stichoza/google-translate-php ^4.0 -> satisfiable by stichoza/google-translate-php[v4.0.0, v4.0.1, v4.0.2, v4.1.0].
    - tanmuhittin/laravel-google-translate 2.0.3 requires stichoza/google-translate-php ^4.0 -> satisfiable by stichoza/google-translate-php[v4.0.0, v4.0.1, v4.0.2, v4.1.0].
    - Installation request for barryvdh/laravel-translation-manager ^0.5.9 -> satisfiable by barryvdh/laravel-translation-manager[0.5.x-dev, v0.5.9].

**Comment by ustenko** [comment]
remove from composer
"barryvdh/laravel-translation-manager"
"tanmuhittin/laravel-google-translate"

then run 
composer install barryvdh/laravel-translation-manager

**Comment by aryomuzakki** [comment]
Hi, i also have a problem when i tried to add this package in **laravel 8** and i still don't know how to solve it.

```
> composer require barryvdh/laravel-translation-manager
Using version ^0.5.9 for barryvdh/laravel-translation-manager
./composer.json has been updated
Running composer update barryvdh/laravel-translation-manager
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-translation-manager 0.5.x-dev is an alias of barryvdh/laravel-translation-manager dev-master and thus requires it to be installed too.
    - barryvdh/laravel-translation-manager[dev-master, v0.5.9] require tanmuhittin/laravel-google-translate ^2.0.1 -> satisfiable by tanmuhittin/laravel-google-translate[2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - tanmuhittin/laravel-google-translate[2.0.3, ..., 2.0.4] require stichoza/google-translate-php ^4.0 -> satisfiable by stichoza/google-translate-php[v4.0.0, ..., v4.1.1].
    - stichoza/google-translate-php[v4.0.0, ..., v4.1.1] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - tanmuhittin/laravel-google-translate[2.0.1, ..., 2.0.2] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires barryvdh/laravel-translation-manager ^0.5.9 -> satisfiable by barryvdh/laravel-translation-manager[v0.5.9, 0.5.x-dev (alias of dev-master)].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I think this is the main problem
```
    - stichoza/google-translate-php[v4.0.0, ..., v4.1.1] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - tanmuhittin/laravel-google-translate[2.0.1, ..., 2.0.2] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
```
but i don't know how to solve it.

I had laravel jetstream livewire added before i add this package, is that the conflict with illuminate/support?


**Can anybody help, please?**

**Comment by tanmuhittin** [comment]
Looks like stichoza/google-translate-php does not support php 8 yet.

ping @stichoza

**Comment by tanmuhittin** [comment]
This problem should be fixed with new release https://github.com/Stichoza/google-translate-php/releases/tag/v4.1.2

**Comment by aryomuzakki** [comment]
That's a great help, it works.
Thank you very much.
