### ISSUE TITLE
Use key for Auto Translation when base language is not found

### ISSUE THREAD

**Issue by peterjaap** [barryvdh/laravel-translation-manager#378]
Scenario;
- My keys are English strings
- My base language is English
- My target language is Dutch
- I'm using the Google Auto Translate option

The Translation Manager shows;

![image](https://user-images.githubusercontent.com/431360/97833535-db6e9000-1cd5-11eb-8c03-272878533ecb.png)

This is because I don't have an English "translation" for the English string.

When I start the Auto translate option, I now get [this error](https://flareapp.io/share/Lm8vlkM7#F51);

```
Argument 1 passed to Illuminate\Support\Str::Tanmuhittin\LaravelGoogleTranslate\{closure}() must be of the type string, null given, called in /data/kapiteinkoko/app2/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 88
```

The quick fix is this, but I'm not sure this is the right way to fix this in all scenarios;

```diff
- $translated_text = Str::apiTranslateWithAttributes($base_string->value, $newLocale, $base_locale);
+ $translated_text = Str::apiTranslateWithAttributes($base_string->value ?? $base_string->key, $newLocale, $base_locale);
```

**Comment by Wiz-Amit** [comment]
Same issue

**Comment by Wiz-Amit** [comment]
Fix this using by #387

**Comment by keyur-nextgen** [comment]
not solved 
 i have         Str::macro('apiTranslateWithAttributes', function (string $text, string $locale, string $base_locale = null)  line

**Comment by HyperDesignCo** [comment]
- $translated_text = Str::apiTranslateWithAttributes($base_string->value, $newLocale, $base_locale);

where this file located
