### ISSUE TITLE
Accessing web interface with ACL

### ISSUE THREAD

**Issue by MarlonEtiene** [barryvdh/laravel-translation-manager#38]
Hello,

I am using zizaco/entrust to manager my ACL and I like to give access to the web interface only for determinated roles(admins or/and super-admins). Where can I validate my ACL role?

**Comment by barryvdh** [comment]
L5? you can set the filter on the config.

**Comment by MarlonEtiene** [comment]
Yes L5. Can you give an example?

**Comment by MarlonEtiene** [comment]
Barry I really not have idea how to set filter in the config file, can you help?

**Comment by barryvdh** [comment]
Publish the config, open your local config/translation-manager.php file and change route.middleware to use your own middleware filter. Default is auth.

**Comment by MarlonEtiene** [comment]
Hello!
Just in the middleware, ok!
his package is awesome, now I can manage the translations easy, and sometimes I can give this work for my clients.
Thank you!
