### ISSUE TITLE
Publishing views

### ISSUE THREAD

**Issue by Drifeter** [barryvdh/laravel-translation-manager#39]
Hi,
is there a way to publish the views to my laravel folder?
I'm using laravel 4.2 and so the branch 0.1
I would like to make a few changes to the views, but i'm worried that if I make it in the vendor folder, one day I would do a composer update and they would be overriden.
How can I make shure that wouldn't happen?

**Comment by barryvdh** [comment]
http://laravel.com/docs/4.2/packages#package-views

**Comment by Drifeter** [comment]
OMG, sorry for the noobish question...
I've researched it, and tryed it, but it didn't work before.
I think I might have used a \ instead of a / or something like that.

It's working now, sorry again :)
