### ISSUE TITLE
Some groups don't get imported on different PC

### ISSUE THREAD

**Issue by emilsrits** [barryvdh/laravel-translation-manager#392]
Under `/resources/lang/en` I have:
```
admin
    auth.php
    common.php
    validation.php
auth.php
common.php
pagination.php
passwords.php
validation.php
```

On PC A (Windows) these groups don't get imported:
```
admin
  common.php
  validation.php
```
`admin/auth.php` does get imported though...

On PC B (Ubuntu WSL2) everything gets imported.

___

I tried both - web interface and `php artisan translations:import`, also tried to reset the translations.

They don't appear in groups select dropdown and database.

Package Version: 0.5.10
Laravel Version: 8

[There seems to have been a "fix" for this, yet it is still happening](https://github.com/barryvdh/laravel-translation-manager/pull/121)

**Comment by suonsamoun** [comment]
Could u try to run this command: php artisan translations:import? 
I am facing the same problem when clicking on the button Import Group, but using command work for me.

Package Version: 0.5.10
Laravel Version: 7
