### ISSUE TITLE
Can't export vendor groups

### ISSUE THREAD

**Issue by gjm** [barryvdh/laravel-translation-manager#393]
Hi.

I have a vendor language group in `resources/lang/vendor/ui`. It gets imported correctly as `vendor/ui` and the translation keys appear normally. When I try to publish or export the edited changes I get an error:

```
file_put_contents(<root_dir>/resources/lang/vendor/ui/en/en/vendor/ui.php): failed to open stream: No such file or directory
```

There's an extra `en` in the path. Should be an easy fix.

**Comment by gjm** [comment]
@barryvdh ping...

**Comment by mvehar** [comment]
The issue is in line 295 inside src/Manager.php -> 
``` 
$path = $path.DIRECTORY_SEPARATOR.$locale.DIRECTORY_SEPARATOR.$group.'.php';
```

Here the group is vendor/ui, but the $path was already modified in lines 278
```
    if ($vendor) {
                            $path = $basePath.'/'.$group.'/'.$locale;
                            $locale_path = Str::after($group, '/');
                        }
```
Creating path as: LANGDIR + (vendor/ui) + locale + locale + (vendor/ui).php
Expected:  LANGDIR + (vendor/ui) + locale + messages.php


Solution is probably changing line 295, if vendor then
``` 
$path = $path.DIRECTORY_SEPARATOR.'messages.php';
```

**Comment by buzzclue** [comment]
Not able to export vendor

**Comment by gjm** [comment]
Is @barryvdh still actively maintaining this package? There is no response...

**Comment by barryvdh** [comment]
Yes, is there a PR for this?

**Comment by gjm** [comment]
I don't know if @buzzclue or @mvehar  made one... If not I can give it a try...

**Comment by mvehar** [comment]
Go ahead, I excluded vendor packages for now in projects
