### ISSUE TITLE
Export functionality not working

### ISSUE THREAD

**Issue by ksidibe** [barryvdh/laravel-translation-manager#40]
Great idea. This exactly what I'd been looking for. However, I have a problem.
I'm using laravel 4.2 and version 0.1.x of Translation Manaher. The Export functionality is not working for me neither through the browser button nor from the console using artisan. I have even sudo to ran the command. Still nothing.
Any suggestions?
Thanks in advance

**Comment by barryvdh** [comment]
Perhaps chmod 777 the lang dir?

**Comment by ksidibe** [comment]
@barryvdh, thanks for your prompt reply. But I found out that permission was not the problem. It looks like Translation Manager runs the export on the default database configured in config.php.
I'm building a multi-tenant app in which each client has a segregated db. So, every request is routed to the db belonging to that user. However, Translation manager always runs against the default db regardless of what db the session is set to.
To work around that, I changed the default db to the dev db and an the export. That worked.
Thanks again and great tool!
