### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by djoudi** [barryvdh/laravel-translation-manager#407]
composer require barryvdh/laravel-translation-manager
Using version ^0.5.10 for barryvdh/laravel-translation-manager
./composer.json has been updated
Running composer update barryvdh/laravel-translation-manager
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-translation-manager 0.5.x-dev is an alias of barryvdh/laravel-translation-manager dev-master and thus requires it to be installed too.      
    - barryvdh/laravel-translation-manager[dev-master, v0.5.10] require tanmuhittin/laravel-google-translate ^2.0.1 -> satisfiable by tanmuhittin/laravel-google-translate[2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - tanmuhittin/laravel-google-translate[2.0.3, ..., 2.0.4] require google/cloud-translate ^1.7.4 -> satisfiable by google/cloud-translate[v1.7.4, ..., v1.12.3].
    - google/cloud-translate[v1.7.4, ..., v1.12.3] require google/gax ^1.1 -> satisfiable by google/gax[1.1.0, ..., v1.11.4].
    - google/gax[v1.9.0, ..., v1.11.4] require google/auth ^1.18.0 -> satisfiable by google/auth[v1.18.0].
    - google/auth v1.18.0 requires psr/cache ^1.0|^2.0 -> found psr/cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - google/gax[1.1.0, ..., v1.8.0] require guzzlehttp/psr7 ^1.2 -> found guzzlehttp/psr7[1.2.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - tanmuhittin/laravel-google-translate[2.0.1, ..., 2.0.2] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires barryvdh/laravel-translation-manager ^0.5.10 -> satisfiable by barryvdh/laravel-translation-manager[v0.5.10, 0.5.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require barryvdh/laravel-translation-manager:*" to figure out if any version is installable, or "composer require barryvdh/laravel-translation-manager:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by inkomomutane** [comment]
@djoudi try this command : `composer update --ignore-platform-reqs`.
if it didn't work check if the symfony version is 6 if it is, you need to upgrade you php version to 8.
