### ISSUE TITLE
How to use with laravel 9?

### ISSUE THREAD

**Issue by Jonston** [barryvdh/laravel-translation-manager#427]
Laravel 9 default lang directory is 'lang'.Your package user 'resources/lang'.What i need to do to fix that?

**Comment by sabbaman** [comment]
I'm using the latest version (0.6.3, Laravel 9) and the language path is correctly loaded from the app base.path, which is correctly /lang.

Are you having this problem on an updated project or one started from scratch with Laravel 9?
