### ISSUE TITLE
Call to undefined method [package]

### ISSUE THREAD

**Issue by vdomah** [barryvdh/laravel-translation-manager#43]
After adding provider of this package to app.php such error appears. 
`at ServiceProvider->__call('package', array('barryvdh/laravel-translation-manager'))`

Found similar problem here https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention
but there problem described where all packages that use package() method crashed. But in my case for example laracasts\flash works fine.

**Comment by barryvdh** [comment]
Make sure you use the 0.2.x branch (`0.2.x@dev`)

**Comment by vdomah** [comment]
yes, there was "barryvdh/laravel-translation-manager": "0.1.*" in composer.json. It download that version after I run `composer require barryvdh/laravel-translation-manager`.
And yes, when I changed to "0.2.x@dev" package was installed and works now. But also tried before `"barryvdh/laravel-translation-manager": "0.2.x"` (from readme) and it says that package is not found.
Now it's ok, thanks!
