### ISSUE TITLE
Can this package work under Laravel 10?

### ISSUE THREAD

**Issue by cleargoal** [barryvdh/laravel-translation-manager#446]
I didn't know the answer, but I tried to use it with the newest Laravel.

I published migrations, config, and views by the commands you provided in readme.
But I have not published either ManagerServiceProvider.php or TranslationServiceProvider.php and not the routes file.
Is it the correct published result? What did I miss?

Problem: Now I can't start the translation manager at http://yourdomain.com/translations.

Please, direct me or fix this.
Thank you!

**Comment by maha-oueghlani** [comment]
are you have a solution ?

**Comment by cleargoal** [comment]
No, I haven't.

**Comment by vadimwe** [comment]
Yes. It works as expected. Check middleware settings in trasnlation-manager config.

```
'route' => [
        'prefix' => 'translations',
        'middleware' => [
	        'web',
	        'auth',  // check if you are logged in
	],
    ],
```

**Comment by cleargoal** [comment]
Thank you!
Now it works in Laravel 11 too.
So, it's solved.

**Comment by cleargoal** [comment]
I close it as I'm starter
