### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by MarlonEtiene** [barryvdh/laravel-translation-manager#45]
Hi Barry

When I try to install the package with "barryvdh/laravel-translation-manager: 0.2.x" I get the message:

```
Problem 1
    - The requested package barryvdh/laravel-translation-manager could not be found in any version, there may be a typo in the package name.`
```

If I use "barryvdh/laravel-translation-manager: dev-master" It's work fine.

Not really an issue, I am just making you know

**Comment by Casinelli** [comment]
I think the correct syntax for composer would be '''"barryvdh/laravel-translation-manager": "0.2.*"'''

**Comment by MarlonEtiene** [comment]
I tryed this "barryvdh/laravel-translator-manager": "0.2.*" and composer say
```
Problem 1
    - Installation request for barryvdh/laravel-translation-manager 0.2.* -> satisfiable by barryvdh/laravel-translation-manager[0.2.x-dev].
    - Removal request for barryvdh/laravel-translation-manager == 0.2.9999999.9999999-dev
```
Then I tryed "barryvdh/laravel-translator-manager": "0.2.x-dev" and worked like a charm :)

**Comment by adis-me** [comment]
As you can see on https://packagist.org/packages/barryvdh/laravel-translation-manager, currently the correct way is `"barryvdh/laravel-translation-manager": "0.2.*@dev"`. @MarlonEtiene suggestion did not worked for me.

**Comment by mendrinos** [comment]
There should be an active branch 0.2 to the Github repo to work - now you have just the master and the 0.1.

In order to work with Laravel 5 I had to have it like that:

"barryvdh/laravel-translation-manager": "dev-master"

which is not super safe for production env..
