### ISSUE TITLE
Method make does not exist

### ISSUE THREAD

**Issue by sameerpanjwani** [barryvdh/laravel-translation-manager#46]
In your Controller.php you have a \View::make command which doesn't seem to work with my L5 site. Any ideas why? When I changed it to just:

view('translation-manager::index') 

it worked.

Btw I installed "barryvdh/laravel-translation-manager": "0.2.*-dev"

**Comment by barryvdh** [comment]
I replaced the `View::make` and other facades with helpers. See above commit.
