### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by mendrinos** [barryvdh/laravel-translation-manager#54]
This error came up after upgrading to Laravel 5.1..

Any ideas?

![screen shot 2015-06-13 at 8 48 54 am](https://cloud.githubusercontent.com/assets/1592441/8142326/9c8b7794-11ab-11e5-9304-007df916f93c.png)

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-translation-manager/pull/52

**Comment by barryvdh** [comment]
Fixed by #52
