### ISSUE TITLE
Problem with laravel 5.0.x 

### ISSUE THREAD

**Issue by diaxis** [barryvdh/laravel-translation-manager#55]
Hi you just pushed a new opdate to 0.2.0 requiring laravel 5.1 The problem is we cannot use 5.1 due to the php requirement and our lack of control over that in our servers. 

And all you version use either 4.2 or 5.1. Any way we can have a version using 5.0?

**Comment by barryvdh** [comment]
Does https://github.com/barryvdh/laravel-translation-manager/commit/19207f1fc1548372ec434ff78f55e063afcebf1b fix it for you?

**Comment by diaxis** [comment]
Yes thanki you!
