### ISSUE TITLE
Issues with 5.0.33 - Will not install.

### ISSUE THREAD

**Issue by grumpysi** [barryvdh/laravel-translation-manager#56]
Looks like it should be 5.0.33 compatible.  Not sure why it won't install.

Problem 1
    - Installation request for barryvdh/laravel-translation-manager ^0.2.0 -> satisfiable by barryvdh/laravel-translation-manager[v0.2.0].
    - Conclusion: remove laravel/framework v5.0.33
    - Conclusion: don't install laravel/framework v5.0.33
    - barryvdh/laravel-translation-manager v0.2.0 requires illuminate/translation 5.1.x -> satisfiable by illuminate/translation[v5.1.1, v5.1.2].
    - don't install illuminate/translation v5.1.1|don't install laravel/framework v5.0.33
    - don't install illuminate/translation v5.1.2|don't install laravel/framework v5.0.33
    - Installation request for laravel/framework == 5.0.33.0 -> satisfiable by laravel/framework[v5.0.33].

**Comment by barryvdh** [comment]
Can you try 0.2.0@dev?

**Comment by grumpysi** [comment]
"barryvdh/laravel-translation-manager": "0.2.0@dev" - Doesn't work.
"barryvdh/laravel-translation-manager": "@dev" - Works

Thanks.

**Comment by barryvdh** [comment]
Sorry meant 0.2.x@dev. But I'll tag `v0.2.1`

**Comment by grumpysi** [comment]
Config would not publish but that might be a problem my end.  I've grafted in the routes manually.
Thanks again.  Nice and useful tool.
