### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-translation-manager#6]
THis should also allow for deeper levels in groupnames. Like `app/lang/en/admin/core/messages.php` -> group `admin.core.messages`, both in importing, exporting and searching.

**Comment by tommedema** [comment]
Does this work for Laravel 4 too?

**Comment by markwalet** [comment]
Couldn't you just import deeper files with an / instead of .?
Something like admin/subfolder/core.array_in_file
