### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by pepodev** [barryvdh/laravel-translation-manager#62]
Warning: Ambiguous class resolution, "CreateTranslationsTable" was found in both "$baseDir . '/database/migrations/2014_04_02_193005_create_translations_table.php" and "/vagrant/spike/releases/devel/vendor/barryvdh/laravel-translation-manager/database/migrations/2014_04_02_193005_create_translations_table.php", the first will be used.

**Comment by barryvdh** [comment]
I guess I shouldn't autoload that in L5.
What version are you using?

**Comment by pepodev** [comment]
5.1

**Comment by drndavi** [comment]
this is still happening in 5.1
