### ISSUE TITLE
Delete deprecated keys

### ISSUE THREAD

**Issue by vics80** [barryvdh/laravel-translation-manager#63]
Firs of all. Thank you for this useful plugin.

It's possible to delete the deprecated keys? In other words, I delete some text from the code, but the keys are kept in lang files. Can I clean lang files for deprecated keys?

**Comment by L1lle** [comment]
I have a lot of unused language strings in my files too. This makes it not easy to add new translations.

I think a good simple option would be to import only entries which are already existing in the database.

For example:

    php artisan translations:import --replace_existing

So you can run: 
 
    reset
    find
    import --replace_existing
    publish 

This will leave only used language strings in the files or database.
