### ISSUE TITLE
Versioning idea

### ISSUE THREAD

**Issue by mendrinos** [barryvdh/laravel-translation-manager#74]
Just dropping an idea here - would be good to have a versioning handling for all translations - so if there is a new amendment on one language - to switch to that version view - so the rest of translators to check what's new and what they need to translate for this version.

**Comment by Sennik** [comment]
I agree

**Comment by philippejadin** [comment]
Could "simply" use the versionable trait on the model https://github.com/VentureCraft/revisionable
