### ISSUE TITLE
Nothing to publish

### ISSUE THREAD

**Issue by XaphanBael** [barryvdh/laravel-translation-manager#75]
Fresh laravel 5.1.24 install, i add the "barryvdh/laravel-translation-manager": "0.2.1" to my composer.json and perform composer update, so far so good.

Next i add the package to my app.php providers and run: php artisan vendor:publish --provider="Barryvdh\TranslationManager\ManagerServiceProvider" --tag=migrations

It keeps returning: Nothing to publish for tag [migration].

I also tried version 0.2.0, gives the exact same message.

**Comment by RomainSauvaire** [comment]
Hello there,

I just picked the `v0.2.2` with laravel `v5.2.36` and I get the same issue either for `--tag= migrations` or `--tag= config`.

Any clue ?

**Comment by RomainSauvaire** [comment]
Wow, just tested `config:clear` before running the `vendor: publish` and it worked like a charm.
You can close this issue, I'll update the doc ;)
