### ISSUE TITLE
Error when try to access Declaration of Barryvdh\TranslationManager\Translator::get() should be compatible with Illuminate\Translation\Translator::get($key, array $replace = Array, $locale = NULL, $fallback = true)

### ISSUE THREAD

**Issue by muzafarali** [barryvdh/laravel-translation-manager#76]
Hi,
i install this extension on Laravel 5.1.x and configure as you instruction it's create database table and import the languages strings but when i try to access from frontend on localhost
http://localhost/laravelbootstrap/public/en/translations
it's give me blow error..

Error
Exception in Translator.php line 6: Declaration of Barryvdh\TranslationManager\Translator::get() should be compatible with Illuminate\Translation\Translator::get($key, array $replace = Array, $locale = NULL, $fallback = true)

i try other combination as well
http://localhost/laravelbootstrap/public/translations

but same error can you help me to sort out this issue..

Thanks

**Comment by christiaandm** [comment]
Same problem im also on 5.1.x only happens when using your version of the TranslationServiceProvider.

**Comment by gdi009** [comment]
The error still exists - just edit the Translator.php and add $fallback = true to the end of get function
