### ISSUE TITLE
change route?

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-translation-manager#77]
I have problems because my routes can't access to /translations

how can I change the route? or add a filter to my route that not allow to access translations

**Comment by dsfser** [comment]
i have this:

'route' => [
        'prefix' => 'translations',
		'as' => 'translations',
        'middleware' => ['auth', 'needsRole:admin|customadmin,true'],
    ],

but how can i make a normal route for translations?

like this:
Route::get('translations', ['as' => 'translations', 'middleware' => ['auth', 'needsRole:admin|customadmin,true'], 'uses' => '???translations???@index']);

**Comment by dsfser** [comment]
nevermind...

found it:

    Route::get('admin/settings/languages', ['as' => 'settings.languages', 'middleware' => ['auth', 'needsRole:admin|customadmin,true'], 'uses' => '\Barryvdh\TranslationManager\Controller@getIndex']);

**Comment by carlituxman** [comment]
We solve using this before in routes:

Route::get('/translations',
'\Barryvdh\TranslationManager\Controller@getIndex');
Route::get('/translations/view/{group?}',
'\Barryvdh\TranslationManager\Controller@getView');



2015-12-18 12:14 GMT+01:00 dsfser <notifications@github.com>:

> nevermind...
>
> found it:
>
> Route::get('admin/settings/languages', ['as' => 'settings.languages', 'middleware' => ['auth', 'needsRole:admin|customadmin,true'], 'uses' => '\Barryvdh\TranslationManager\Controller@getIndex']);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-translation-manager/issues/77#issuecomment-165750923>
> .
>



-- 
*Carlos Jiménez Mora*
*INFORMATIK SOLUCIONES*
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman <https://twitter.com/carlituxman> - carlos@informatik.es

*Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto.*

**Comment by dsfser** [comment]
nice

**Comment by dsfser** [comment]
i have added the routes everything works.

but the links like this one:

    <form action="<?= action('\Barryvdh\TranslationManager\Controller@postAdd', array($group)) ?>" method="POST"  role="form">

still becomes like this:

    <form class="form-inline form-publish" method="POST" action="WEBSITE/**translations**/publish/header" data-remote="true" role="form" data-confirm="Are you sure you want to publish the translations group 'header? This will overwrite existing language files.">
		<input type="hidden" name="_token" value="">
		<button type="submit" class="btn btn-info" data-disable-with="Publishing..">Publish translations</button>
	</form>

**Comment by carlituxman** [comment]
Probably is need to add more routes, but the form not works? whats the form?

2015-12-18 13:50 GMT+01:00 dsfser <notifications@github.com>:

> i have added the routes everything works.
>
> but the links like this one:
>
> <form action="<?= action('\Barryvdh\TranslationManager\Controller@postAdd', array($group)) ?>" method="POST"  role="form">
>
> still becomes like this:
>
> <form class="form-inline form-publish" method="POST" action="WEBSITE/**translations**/publish/header" data-remote="true" role="form" data-confirm="Are you sure you want to publish the translations group 'header? This will overwrite existing language files.">
>     <input type="hidden" name="_token" value="">
>     <button type="submit" class="btn btn-info" data-disable-with="Publishing..">Publish translations</button>
> </form>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-translation-manager/issues/77#issuecomment-165770617>
> .
>



-- 
*Carlos Jiménez Mora*
*INFORMATIK SOLUCIONES*
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman <https://twitter.com/carlituxman> - carlos@informatik.es

*Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto.*

**Comment by dsfser** [comment]
all the forms have a POST action.

i need the link to be: http://######.nl/admin/settings/languages/find

instead of: http://######.nl/translations/find

those are my routes:

    Route::get('admin/settings/languages', ['as' => 'settings.languages', 'middleware' => ['auth', 'needsRole:admin|customadmin,true'], 'uses' => '\Barryvdh\TranslationManager\Controller@getIndex']);

    Route::get('admin/settings/languages/view/{group}', ['as' => 'settings.languages.view', 'middleware' => ['auth', 'needsRole:admin|customadmin,true'], 'uses' => '\Barryvdh\TranslationManager\Controller@getView']);

and i removed the route in the settings file. (config/translation-manager.php)

**Comment by carlituxman** [comment]
but is not the problem with your another routes then

**Comment by rbruhn** [comment]
In case anyone drops by this issue, here are the route definitions I use.

Caveat: I'm using AdminLTE and wanted the translations to show in my admin section. It involved making a copy of the translation controller, publishing and editing the view, then replacing the hand coded "action" helpers in the controller and view using the "route" helper. So, these routes simply show what you need, and adjusting them for your application is up to you.

    $router->get('translations', [
        'uses' => 'TranslationsController@getIndex',
        'as' => 'admin.translations.index'
    ]);
    
    $router->get('translations/view/{group?}', [
        'uses' => 'TranslationsController@getView',
        'as' => 'admin.translations.view'
    ]);
    
    $router->post('translations/edit/{group?}', [
        'uses' => 'TranslationsController@postEdit',
        'as' => 'admin.translations.edit'
    ]);
    
    $router->post('translations/import', [
        'uses' => 'TranslationsController@postImport',
        'as' => 'admin.translations.import'
    ]);
    
    $router->post('translations/find', [
        'uses' => 'TranslationsController@postFind',
        'as' => 'admin.translations.find'
    ]);
    
    $router->post('translations/publish/{group}', [
        'uses' => 'TranslationsController@postPublish',
        'as' => 'admin.translations.publish'
    ]);
    
    $router->post('translations/add/{group}', [
        'uses' => 'TranslationsController@postAdd',
        'as' => 'admin.translations.add'
    ]);
    
    $router->post('translations/delete/{group}/{key}', [
        'uses' => 'TranslationsController@postDelete',
        'as' => 'admin.translations.delete'
    ]);
