### ISSUE TITLE
Requirements could not be resolved [Composer]

### ISSUE THREAD

**Issue by mrdezzods** [barryvdh/laravel-translation-manager#81]
This is what i get. Any ideas?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Installation request for barryvdh/laravel-translation-manager 0.2.1 -> satisfiable by barryvdh/laravel-translation-manager[v0.2.1].
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - barryvdh/laravel-translation-manager v0.2.1 requires illuminate/translation 5.0.x|5.1.x -> satisfiable by illuminate/translation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - don't install illuminate/translation v5.0.0|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.22|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.25|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.26|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.28|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.33|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.0.4|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.13|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.16|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.2|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.20|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.22|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.25|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.28|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.6|don't install laravel/framework v5.2.0
    - don't install illuminate/translation v5.1.8|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6].
```

**Comment by MightySCollins** [comment]
Same problem, it seems the latest commits have not been versioned. Try using `"barryvdh/laravel-translation-manager": "0.2.x-dev"` it seemed to work for me when using Laravel 5.2.

**Comment by samfrjn11** [comment]
`Problem 1
    - Installation request for barryvdh/laravel-translation-manager 0.2.x-dev -> satisfiable by barryvdh/laravel-translation-manager[0.2.x-dev].
    - Conclusion: remove symfony/finder v3.0.2
    - Conclusion: don't install symfony/finder v3.0.2
    - barryvdh/laravel-translation-manager 0.2.x-dev requires symfony/finder ~2.3 -> satisfiable by symfony/finder[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - Can only install one of: symfony/finder[v2.8.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.8.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.8.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.10, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.11, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.12, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.13, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.14, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.15, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.16, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.17, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.18, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.19, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.20, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.21, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.22, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.23, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.24, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.25, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.26, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.27, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.28, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.29, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.3, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.30, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.31, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.32, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.33, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.34, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.35, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.36, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.37, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.4, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.5, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.6, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.7, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.8, v3.0.2].
    - Can only install one of: symfony/finder[v2.3.9, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.10, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.3, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.4, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.5, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.6, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.7, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.8, v3.0.2].
    - Can only install one of: symfony/finder[v2.4.9, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.10, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.11, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.12, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.3, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.4, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.5, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.6, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.7, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.8, v3.0.2].
    - Can only install one of: symfony/finder[v2.5.9, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.10, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.11, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.12, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.13, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.3, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.4, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.5, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.6, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.7, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.8, v3.0.2].
    - Can only install one of: symfony/finder[v2.6.9, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.0, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.1, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.2, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.3, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.4, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.5, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.6, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.7, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.8, v3.0.2].
    - Can only install one of: symfony/finder[v2.7.9, v3.0.2].
    - Installation request for symfony/finder == 3.0.2.0 -> satisfiable by symfony/finder[v3.0.2].`

using the -dev doesn't help :(

**Comment by webproteam** [comment]
Hello, @mrdezzods
Did you solve your issue?
Can you let me know if you had solved your issues?
