### ISSUE TITLE
"Class does not exist" error in Laravel 5.2.10

### ISSUE THREAD

**Issue by fadion** [barryvdh/laravel-translation-manager#84]
Installed and configured as in the manual. Tried adding the provider in `config/app.php` as either a string or `Barryvdh\TranslationManager\ManagerServiceProvider::class`. However, I'm getting this error:

```
ReflectionException in Container.php line 738:
Class does not exist
```

and the first 10 lines of the stack, if it helps in any way:

```
in Container.php line 738
at ReflectionClass->__construct('') in Container.php line 738
at Container->build('', array()) in Container.php line 633
at Container->make('', array()) in Application.php line 674
at Application->make('') in Pipeline.php line 123
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Router.php line 705
```

Tried debugging, but I couldn't find what's wrong. Hope you can reproduce and find out what's causing the error.

**Comment by jpmurray** [comment]
I'm having the same trouble. Last time I had this kind of error was (on an another package) trouble with accessing the config file, but in this case it seems just fine, so I don't really get it either.

And the title should read "Class does not exists" ;-)

**Comment by jpmurray** [comment]
I'm having the same trouble. Last time I had this kind of error was (on an another package) trouble with accessing the config file, but in this case it seems just fine, so I don't really get it either.

If i try to access `/traslations` I'm redirected to `/` with no error. If I empty the middleware parameter in `config/translation-manager.php`, I get the error mentionned by @fadion rather then being redirected to `/`.

And the title should read "Class does not exists" ;-)

**Comment by jpmurray** [comment]
Edit, I found the problem, see #85

**Comment by fadion** [comment]
Great job @jpmurray. I'll test it out and will let you know.

**Comment by jpmurray** [comment]
@barryvdh if you want, you should close this as per #86 also.
