### ISSUE TITLE
Unable to install with Laravel 5.2.11

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-translation-manager#90]
Composer dumps a lot of messages, and then reverts the composer file.

**Comment by cre8websolutions** [comment]
Apparently needs `illuminate/translation`. Not clear from the readme.

**Comment by GregoryClaeyssens** [comment]
Same issue here, L5.2.11

**Comment by robbiepaul** [comment]
I fixed it for now by using `"barryvdh/laravel-translation-manager": "0.2.x-dev"`

I think @barryvdh just hasn't had a chance to push the `v0.2.2` tag up yet

**Comment by Stayallive** [comment]
@barryvdh would be nice if the release got tagged if possible :+1:

**Comment by RomainSauvaire** [comment]
I would really appreciate it to be tagged :)

**Comment by barryvdh** [comment]
Tagged!

**Comment by RomainSauvaire** [comment]
Woooot, awesome @barryvdh ! Thank you 👍
