### ISSUE TITLE
Custom translation blade view

### ISSUE THREAD

**Issue by andreiculda** [barryvdh/laravel-translation-manager#93]
Hi @barryvdh. This is a really nice package and work great with Laravel 5.2. This will save me a lot of time if I use it for my project.
I would really love to be able to set a custom blade view in my resources\views path, to be able to then use my app template with:

``` javascript
@extends('app.template')

@section('content')
    laravel-translation-manager resources\views\index.php body content 
@endsection
```

How would i go about doing this?

Thanks!

**Comment by andreiculda** [comment]
Ok I figured it out. In my `resources\views\vendor` folder I created a new folder `translation-manager` where i put `index.blade.php` and pasted the contents of `laravel-translation-manager resources\views\index.php`. From here it's fairly easy to change `php` code to `blade` compatible code, so it will be more easy to read.

It would be nice though to have this in the installation walk-through and also a blade template for it.

**Comment by ejeanneaubc** [comment]
+1

**Comment by duikb00t** [comment]
+1

**Comment by RogueSheep-nl** [comment]
+1 
& thanks @andreiculda
