### ISSUE TITLE
Export arrays in syntax sugar version for new PHP 5.x, 7.x

### ISSUE THREAD

**Issue by shakaran** [barryvdh/laravel-translation-manager#94]
For export translations the app is using var_export:
https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Manager.php#L144

Producing a ugly/long code based in array(array(...)).

I found that is pretty easy to read when you have big translation files and mostly for non IT people if we use the new syntax available based in brackets [[...]]

They are several ways to achieve this (since php doesn't offer a native way to use var_export() http://php.net/manual/es/function.var-export.php with the new syntax sugar), but it is easily achievable with regex.

Some examples here:

http://stackoverflow.com/questions/24316347/how-to-format-var-export-to-php5-4-array-syntax

So, could you just replace this behaviour for new versions? It would have pretty nice for laravel artisans :)

**Comment by barryvdh** [comment]
No sorry, I think its more reliable to use the default function.

**Comment by shakaran** [comment]
@barryvdh ok, I respect your opinion as you are the original author, but it could be at least a behaviour optional, maybe enabled in config? I was surprised of how fast you close this simple issue.

It is a pity that I have to fork the project onfly for apply this easy patch. I understand that probably some generation could lead to bugs, but for that you make tests and you can really ensure a right behaviour with a good bulletproof unit testing. I mean, I think that Laravel is a great product, but it should be proactive and adopt new things like this and limit his users (at least I see this from other products like Symfony). Because probably in a near future the final output from new PHP version would be optional or only output in this sugar syntax.

But anyways, if you still didn't consider this, thanks for your time, I undertand that probably is a sideproject and you cannot spent a lot time on it.

**Comment by barryvdh** [comment]
The reason I use this format is because it's a simple function and reliable. I'm sure we can replicate the function for the new output, but that is more error prone.
The old array syntax is not going away any time soon, and if so, the output of var_export would be changed also I guess.

If you submit a clean PR with an optional flag to use a custom export function (with short array syntax), I'll consider it :)

**Comment by shakaran** [comment]
@barryvdh Thanks for reconsider it :) I will submit you a clean PR and with some tests too, about the flag I didn't know how to set from config, but I will look how other laravel projects sets this (I came from the Symfony world that it is based from config.yml files)

About the sugar syntax in new PHP version, there is [the #71057 PHP bug report](https://bugs.php.net/bug.php?id=71057) that I am trying to push again if the developers reconsider this as useful in a flag. I mention this github issue too in a comment for that report in case that they found useful cases where this bevahiour is very useful.
